// flow-typed signature: b9ea2c5d81c1359cc817e7185a12ba79
// flow-typed version: <<STUB>>/gatsby-source-wordpress_vnext/flow_v0.83.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'gatsby-source-wordpress'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'gatsby-source-wordpress' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'gatsby-source-wordpress/fetch' {
  declare module.exports: any;
}

declare module 'gatsby-source-wordpress/gatsby-node' {
  declare module.exports: any;
}

declare module 'gatsby-source-wordpress/http-exception-handler' {
  declare module.exports: any;
}

declare module 'gatsby-source-wordpress/normalize' {
  declare module.exports: any;
}

declare module 'gatsby-source-wordpress/output-color' {
  declare module.exports: any;
}

declare module 'gatsby-source-wordpress/request-in-queue' {
  declare module.exports: any;
}

declare module 'gatsby-source-wordpress/scripts/download-test-data' {
  declare module.exports: any;
}

// Filename aliases
declare module 'gatsby-source-wordpress/fetch.js' {
  declare module.exports: $Exports<'gatsby-source-wordpress/fetch'>;
}
declare module 'gatsby-source-wordpress/gatsby-node.js' {
  declare module.exports: $Exports<'gatsby-source-wordpress/gatsby-node'>;
}
declare module 'gatsby-source-wordpress/http-exception-handler.js' {
  declare module.exports: $Exports<'gatsby-source-wordpress/http-exception-handler'>;
}
declare module 'gatsby-source-wordpress/index' {
  declare module.exports: $Exports<'gatsby-source-wordpress'>;
}
declare module 'gatsby-source-wordpress/index.js' {
  declare module.exports: $Exports<'gatsby-source-wordpress'>;
}
declare module 'gatsby-source-wordpress/normalize.js' {
  declare module.exports: $Exports<'gatsby-source-wordpress/normalize'>;
}
declare module 'gatsby-source-wordpress/output-color.js' {
  declare module.exports: $Exports<'gatsby-source-wordpress/output-color'>;
}
declare module 'gatsby-source-wordpress/request-in-queue.js' {
  declare module.exports: $Exports<'gatsby-source-wordpress/request-in-queue'>;
}
declare module 'gatsby-source-wordpress/scripts/download-test-data.js' {
  declare module.exports: $Exports<'gatsby-source-wordpress/scripts/download-test-data'>;
}
