// flow-typed signature: d4034947d71f0c015aeb5ee8e60da147
// flow-typed version: <<STUB>>/react-size-components_v^2.0.13/flow_v0.83.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'react-size-components'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'react-size-components' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'react-size-components/babel.config' {
  declare module.exports: any;
}

declare module 'react-size-components/build/react-size-components.cjs' {
  declare module.exports: any;
}

declare module 'react-size-components/build/react-size-components.esm' {
  declare module.exports: any;
}

declare module 'react-size-components/docs/component/Child' {
  declare module.exports: any;
}

declare module 'react-size-components/docs/component/component.stories' {
  declare module.exports: any;
}

declare module 'react-size-components/docs/component/Debounce' {
  declare module.exports: any;
}

declare module 'react-size-components/docs/component/ID' {
  declare module.exports: any;
}

declare module 'react-size-components/docs/component/Parent' {
  declare module.exports: any;
}

declare module 'react-size-components/docs/custom/Advanced' {
  declare module.exports: any;
}

declare module 'react-size-components/docs/custom/Child' {
  declare module.exports: any;
}

declare module 'react-size-components/docs/custom/component.stories' {
  declare module.exports: any;
}

declare module 'react-size-components/docs/general/General' {
  declare module.exports: any;
}

declare module 'react-size-components/docs/general/general.stories' {
  declare module.exports: any;
}

declare module 'react-size-components/docs/inview/Child' {
  declare module.exports: any;
}

declare module 'react-size-components/docs/inview/inview.stories' {
  declare module.exports: any;
}

declare module 'react-size-components/docs/inview/MultipleChildren' {
  declare module.exports: any;
}

declare module 'react-size-components/docs/mobile/Child' {
  declare module.exports: any;
}

declare module 'react-size-components/docs/mobile/mobile.stories' {
  declare module.exports: any;
}

declare module 'react-size-components/docs/orientation/Child' {
  declare module.exports: any;
}

declare module 'react-size-components/docs/orientation/orientation.stories' {
  declare module.exports: any;
}

declare module 'react-size-components/docs/performance/AnotherChild' {
  declare module.exports: any;
}

declare module 'react-size-components/docs/performance/Child' {
  declare module.exports: any;
}

declare module 'react-size-components/docs/performance/Parent' {
  declare module.exports: any;
}

declare module 'react-size-components/docs/performance/performance.stories' {
  declare module.exports: any;
}

declare module 'react-size-components/docs/performance/SlowChild' {
  declare module.exports: any;
}

declare module 'react-size-components/docs/performance/SlowParent' {
  declare module.exports: any;
}

declare module 'react-size-components/docs/performance/Test' {
  declare module.exports: any;
}

declare module 'react-size-components/docs/window/Child' {
  declare module.exports: any;
}

declare module 'react-size-components/docs/window/ID' {
  declare module.exports: any;
}

declare module 'react-size-components/docs/window/window.stories' {
  declare module.exports: any;
}

declare module 'react-size-components/rollup.config' {
  declare module.exports: any;
}

declare module 'react-size-components/scripts/readme' {
  declare module.exports: any;
}

declare module 'react-size-components/src/__tests__/create-initial-state' {
  declare module.exports: any;
}

declare module 'react-size-components/src/Compose' {
  declare module.exports: any;
}

declare module 'react-size-components/src/configurations/component' {
  declare module.exports: any;
}

declare module 'react-size-components/src/configurations/index' {
  declare module.exports: any;
}

declare module 'react-size-components/src/configurations/inView' {
  declare module.exports: any;
}

declare module 'react-size-components/src/configurations/mobile' {
  declare module.exports: any;
}

declare module 'react-size-components/src/configurations/orientation' {
  declare module.exports: any;
}

declare module 'react-size-components/src/configurations/types' {
  declare module.exports: any;
}

declare module 'react-size-components/src/configurations/windowSize' {
  declare module.exports: any;
}

declare module 'react-size-components/src/createConfigurationInjector' {
  declare module.exports: any;
}

declare module 'react-size-components/src/index' {
  declare module.exports: any;
}

declare module 'react-size-components/src/initializers' {
  declare module.exports: any;
}

declare module 'react-size-components/src/LazyEvent' {
  declare module.exports: any;
}

declare module 'react-size-components/ssr/__tests__/server-side-render.test' {
  declare module.exports: any;
}

declare module 'react-size-components/ssr/build/bundle' {
  declare module.exports: any;
}

declare module 'react-size-components/ssr/index' {
  declare module.exports: any;
}

declare module 'react-size-components/ssr/Page' {
  declare module.exports: any;
}

declare module 'react-size-components/ssr/server' {
  declare module.exports: any;
}

declare module 'react-size-components/ssr/template' {
  declare module.exports: any;
}

declare module 'react-size-components/ssr/webpack.config' {
  declare module.exports: any;
}

// Filename aliases
declare module 'react-size-components/babel.config.js' {
  declare module.exports: $Exports<'react-size-components/babel.config'>;
}
declare module 'react-size-components/build/react-size-components.cjs.js' {
  declare module.exports: $Exports<'react-size-components/build/react-size-components.cjs'>;
}
declare module 'react-size-components/build/react-size-components.esm.js' {
  declare module.exports: $Exports<'react-size-components/build/react-size-components.esm'>;
}
declare module 'react-size-components/docs/component/Child.js' {
  declare module.exports: $Exports<'react-size-components/docs/component/Child'>;
}
declare module 'react-size-components/docs/component/component.stories.js' {
  declare module.exports: $Exports<'react-size-components/docs/component/component.stories'>;
}
declare module 'react-size-components/docs/component/Debounce.js' {
  declare module.exports: $Exports<'react-size-components/docs/component/Debounce'>;
}
declare module 'react-size-components/docs/component/ID.js' {
  declare module.exports: $Exports<'react-size-components/docs/component/ID'>;
}
declare module 'react-size-components/docs/component/Parent.js' {
  declare module.exports: $Exports<'react-size-components/docs/component/Parent'>;
}
declare module 'react-size-components/docs/custom/Advanced.js' {
  declare module.exports: $Exports<'react-size-components/docs/custom/Advanced'>;
}
declare module 'react-size-components/docs/custom/Child.js' {
  declare module.exports: $Exports<'react-size-components/docs/custom/Child'>;
}
declare module 'react-size-components/docs/custom/component.stories.js' {
  declare module.exports: $Exports<'react-size-components/docs/custom/component.stories'>;
}
declare module 'react-size-components/docs/general/General.js' {
  declare module.exports: $Exports<'react-size-components/docs/general/General'>;
}
declare module 'react-size-components/docs/general/general.stories.js' {
  declare module.exports: $Exports<'react-size-components/docs/general/general.stories'>;
}
declare module 'react-size-components/docs/inview/Child.js' {
  declare module.exports: $Exports<'react-size-components/docs/inview/Child'>;
}
declare module 'react-size-components/docs/inview/inview.stories.js' {
  declare module.exports: $Exports<'react-size-components/docs/inview/inview.stories'>;
}
declare module 'react-size-components/docs/inview/MultipleChildren.js' {
  declare module.exports: $Exports<'react-size-components/docs/inview/MultipleChildren'>;
}
declare module 'react-size-components/docs/mobile/Child.js' {
  declare module.exports: $Exports<'react-size-components/docs/mobile/Child'>;
}
declare module 'react-size-components/docs/mobile/mobile.stories.js' {
  declare module.exports: $Exports<'react-size-components/docs/mobile/mobile.stories'>;
}
declare module 'react-size-components/docs/orientation/Child.js' {
  declare module.exports: $Exports<'react-size-components/docs/orientation/Child'>;
}
declare module 'react-size-components/docs/orientation/orientation.stories.js' {
  declare module.exports: $Exports<'react-size-components/docs/orientation/orientation.stories'>;
}
declare module 'react-size-components/docs/performance/AnotherChild.js' {
  declare module.exports: $Exports<'react-size-components/docs/performance/AnotherChild'>;
}
declare module 'react-size-components/docs/performance/Child.js' {
  declare module.exports: $Exports<'react-size-components/docs/performance/Child'>;
}
declare module 'react-size-components/docs/performance/Parent.js' {
  declare module.exports: $Exports<'react-size-components/docs/performance/Parent'>;
}
declare module 'react-size-components/docs/performance/performance.stories.js' {
  declare module.exports: $Exports<'react-size-components/docs/performance/performance.stories'>;
}
declare module 'react-size-components/docs/performance/SlowChild.js' {
  declare module.exports: $Exports<'react-size-components/docs/performance/SlowChild'>;
}
declare module 'react-size-components/docs/performance/SlowParent.js' {
  declare module.exports: $Exports<'react-size-components/docs/performance/SlowParent'>;
}
declare module 'react-size-components/docs/performance/Test.js' {
  declare module.exports: $Exports<'react-size-components/docs/performance/Test'>;
}
declare module 'react-size-components/docs/window/Child.js' {
  declare module.exports: $Exports<'react-size-components/docs/window/Child'>;
}
declare module 'react-size-components/docs/window/ID.js' {
  declare module.exports: $Exports<'react-size-components/docs/window/ID'>;
}
declare module 'react-size-components/docs/window/window.stories.js' {
  declare module.exports: $Exports<'react-size-components/docs/window/window.stories'>;
}
declare module 'react-size-components/rollup.config.js' {
  declare module.exports: $Exports<'react-size-components/rollup.config'>;
}
declare module 'react-size-components/scripts/readme.js' {
  declare module.exports: $Exports<'react-size-components/scripts/readme'>;
}
declare module 'react-size-components/src/__tests__/create-initial-state.js' {
  declare module.exports: $Exports<'react-size-components/src/__tests__/create-initial-state'>;
}
declare module 'react-size-components/src/Compose.js' {
  declare module.exports: $Exports<'react-size-components/src/Compose'>;
}
declare module 'react-size-components/src/configurations/component.js' {
  declare module.exports: $Exports<'react-size-components/src/configurations/component'>;
}
declare module 'react-size-components/src/configurations/index.js' {
  declare module.exports: $Exports<'react-size-components/src/configurations/index'>;
}
declare module 'react-size-components/src/configurations/inView.js' {
  declare module.exports: $Exports<'react-size-components/src/configurations/inView'>;
}
declare module 'react-size-components/src/configurations/mobile.js' {
  declare module.exports: $Exports<'react-size-components/src/configurations/mobile'>;
}
declare module 'react-size-components/src/configurations/orientation.js' {
  declare module.exports: $Exports<'react-size-components/src/configurations/orientation'>;
}
declare module 'react-size-components/src/configurations/types.js' {
  declare module.exports: $Exports<'react-size-components/src/configurations/types'>;
}
declare module 'react-size-components/src/configurations/windowSize.js' {
  declare module.exports: $Exports<'react-size-components/src/configurations/windowSize'>;
}
declare module 'react-size-components/src/createConfigurationInjector.js' {
  declare module.exports: $Exports<'react-size-components/src/createConfigurationInjector'>;
}
declare module 'react-size-components/src/index.js' {
  declare module.exports: $Exports<'react-size-components/src/index'>;
}
declare module 'react-size-components/src/initializers.js' {
  declare module.exports: $Exports<'react-size-components/src/initializers'>;
}
declare module 'react-size-components/src/LazyEvent.js' {
  declare module.exports: $Exports<'react-size-components/src/LazyEvent'>;
}
declare module 'react-size-components/ssr/__tests__/server-side-render.test.js' {
  declare module.exports: $Exports<'react-size-components/ssr/__tests__/server-side-render.test'>;
}
declare module 'react-size-components/ssr/build/bundle.js' {
  declare module.exports: $Exports<'react-size-components/ssr/build/bundle'>;
}
declare module 'react-size-components/ssr/index.js' {
  declare module.exports: $Exports<'react-size-components/ssr/index'>;
}
declare module 'react-size-components/ssr/Page.js' {
  declare module.exports: $Exports<'react-size-components/ssr/Page'>;
}
declare module 'react-size-components/ssr/server.js' {
  declare module.exports: $Exports<'react-size-components/ssr/server'>;
}
declare module 'react-size-components/ssr/template.js' {
  declare module.exports: $Exports<'react-size-components/ssr/template'>;
}
declare module 'react-size-components/ssr/webpack.config.js' {
  declare module.exports: $Exports<'react-size-components/ssr/webpack.config'>;
}
