// flow-typed signature: 440d16d67937b6397c639311c4c121ef
// flow-typed version: <<STUB>>/smalldash_v^1.1.20/flow_v0.83.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'smalldash'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'smalldash' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'smalldash/__tests__/module.test' {
  declare module.exports: any;
}

declare module 'smalldash/babel.config' {
  declare module.exports: any;
}

declare module 'smalldash/build/smalldash.cjs' {
  declare module.exports: any;
}

declare module 'smalldash/build/smalldash.esm' {
  declare module.exports: any;
}

declare module 'smalldash/rollup.config' {
  declare module.exports: any;
}

declare module 'smalldash/scripts/create-index' {
  declare module.exports: any;
}

declare module 'smalldash/src/array/__tests__/fill-from.test' {
  declare module.exports: any;
}

declare module 'smalldash/src/array/__tests__/fill-with.test' {
  declare module.exports: any;
}

declare module 'smalldash/src/array/__tests__/uniq.test' {
  declare module.exports: any;
}

declare module 'smalldash/src/array/fill-from' {
  declare module.exports: any;
}

declare module 'smalldash/src/array/fill-with' {
  declare module.exports: any;
}

declare module 'smalldash/src/array/index' {
  declare module.exports: any;
}

declare module 'smalldash/src/array/object-to-array' {
  declare module.exports: any;
}

declare module 'smalldash/src/array/types' {
  declare module.exports: any;
}

declare module 'smalldash/src/array/uniq' {
  declare module.exports: any;
}

declare module 'smalldash/src/async/__tests__/compose-async.test' {
  declare module.exports: any;
}

declare module 'smalldash/src/async/__tests__/debounce.test' {
  declare module.exports: any;
}

declare module 'smalldash/src/async/__tests__/pipe-async.test' {
  declare module.exports: any;
}

declare module 'smalldash/src/async/compose-async' {
  declare module.exports: any;
}

declare module 'smalldash/src/async/debounce' {
  declare module.exports: any;
}

declare module 'smalldash/src/async/index' {
  declare module.exports: any;
}

declare module 'smalldash/src/async/pipe-async' {
  declare module.exports: any;
}

declare module 'smalldash/src/async/throttle' {
  declare module.exports: any;
}

declare module 'smalldash/src/async/types' {
  declare module.exports: any;
}

declare module 'smalldash/src/functional/__tests__/filter.test' {
  declare module.exports: any;
}

declare module 'smalldash/src/functional/__tests__/map-left.test' {
  declare module.exports: any;
}

declare module 'smalldash/src/functional/__tests__/map-right.test' {
  declare module.exports: any;
}

declare module 'smalldash/src/functional/__tests__/map.test' {
  declare module.exports: any;
}

declare module 'smalldash/src/functional/__tests__/side-effects.test' {
  declare module.exports: any;
}

declare module 'smalldash/src/functional/compose' {
  declare module.exports: any;
}

declare module 'smalldash/src/functional/create-array-method-mutable' {
  declare module.exports: any;
}

declare module 'smalldash/src/functional/create-array-method' {
  declare module.exports: any;
}

declare module 'smalldash/src/functional/filter-left' {
  declare module.exports: any;
}

declare module 'smalldash/src/functional/filter-right' {
  declare module.exports: any;
}

declare module 'smalldash/src/functional/filter' {
  declare module.exports: any;
}

declare module 'smalldash/src/functional/index' {
  declare module.exports: any;
}

declare module 'smalldash/src/functional/map-left' {
  declare module.exports: any;
}

declare module 'smalldash/src/functional/map-right' {
  declare module.exports: any;
}

declare module 'smalldash/src/functional/map' {
  declare module.exports: any;
}

declare module 'smalldash/src/functional/pipe' {
  declare module.exports: any;
}

declare module 'smalldash/src/functional/side-effects' {
  declare module.exports: any;
}

declare module 'smalldash/src/functional/types' {
  declare module.exports: any;
}

declare module 'smalldash/src/index' {
  declare module.exports: any;
}

declare module 'smalldash/src/object/__tests__/equals.performance.test' {
  declare module.exports: any;
}

declare module 'smalldash/src/object/__tests__/equals.test' {
  declare module.exports: any;
}

declare module 'smalldash/src/object/equals' {
  declare module.exports: any;
}

declare module 'smalldash/src/object/index' {
  declare module.exports: any;
}

declare module 'smalldash/src/object/types' {
  declare module.exports: any;
}

declare module 'smalldash/src/primitives/__tests__/arrayish.test' {
  declare module.exports: any;
}

declare module 'smalldash/src/primitives/__tests__/nullish.test' {
  declare module.exports: any;
}

declare module 'smalldash/src/primitives/__tests__/numberish.test' {
  declare module.exports: any;
}

declare module 'smalldash/src/primitives/__tests__/objectish.test' {
  declare module.exports: any;
}

declare module 'smalldash/src/primitives/__tests__/stringish.test' {
  declare module.exports: any;
}

declare module 'smalldash/src/primitives/arrayish' {
  declare module.exports: any;
}

declare module 'smalldash/src/primitives/index' {
  declare module.exports: any;
}

declare module 'smalldash/src/primitives/nullish' {
  declare module.exports: any;
}

declare module 'smalldash/src/primitives/numberish' {
  declare module.exports: any;
}

declare module 'smalldash/src/primitives/objectish' {
  declare module.exports: any;
}

declare module 'smalldash/src/primitives/stringish' {
  declare module.exports: any;
}

declare module 'smalldash/src/primitives/types' {
  declare module.exports: any;
}

declare module 'smalldash/src/string/__tests__/camel.test' {
  declare module.exports: any;
}

declare module 'smalldash/src/string/__tests__/capitalize.test' {
  declare module.exports: any;
}

declare module 'smalldash/src/string/__tests__/currency-string.test' {
  declare module.exports: any;
}

declare module 'smalldash/src/string/__tests__/is-lower-case.test' {
  declare module.exports: any;
}

declare module 'smalldash/src/string/__tests__/is-upper-case.test' {
  declare module.exports: any;
}

declare module 'smalldash/src/string/__tests__/kebab.test' {
  declare module.exports: any;
}

declare module 'smalldash/src/string/__tests__/pad-digits.test' {
  declare module.exports: any;
}

declare module 'smalldash/src/string/__tests__/percent.test' {
  declare module.exports: any;
}

declare module 'smalldash/src/string/__tests__/validate-decimal.test' {
  declare module.exports: any;
}

declare module 'smalldash/src/string/accept-strings' {
  declare module.exports: any;
}

declare module 'smalldash/src/string/camel-to-kebab' {
  declare module.exports: any;
}

declare module 'smalldash/src/string/camel-to-pascal' {
  declare module.exports: any;
}

declare module 'smalldash/src/string/camel-to-sentence' {
  declare module.exports: any;
}

declare module 'smalldash/src/string/camel-to-snake' {
  declare module.exports: any;
}

declare module 'smalldash/src/string/camel-to-title' {
  declare module.exports: any;
}

declare module 'smalldash/src/string/camel-to' {
  declare module.exports: any;
}

declare module 'smalldash/src/string/capitalize' {
  declare module.exports: any;
}

declare module 'smalldash/src/string/case-to-case' {
  declare module.exports: any;
}

declare module 'smalldash/src/string/currency-string' {
  declare module.exports: any;
}

declare module 'smalldash/src/string/dollar-string' {
  declare module.exports: any;
}

declare module 'smalldash/src/string/index' {
  declare module.exports: any;
}

declare module 'smalldash/src/string/is-lower-case' {
  declare module.exports: any;
}

declare module 'smalldash/src/string/is-upper-case' {
  declare module.exports: any;
}

declare module 'smalldash/src/string/kebab-to-camel' {
  declare module.exports: any;
}

declare module 'smalldash/src/string/kebab-to-sentence' {
  declare module.exports: any;
}

declare module 'smalldash/src/string/kebab-to-snake' {
  declare module.exports: any;
}

declare module 'smalldash/src/string/kebab-to-title' {
  declare module.exports: any;
}

declare module 'smalldash/src/string/kebab-to' {
  declare module.exports: any;
}

declare module 'smalldash/src/string/pad-digits' {
  declare module.exports: any;
}

declare module 'smalldash/src/string/pad-zero' {
  declare module.exports: any;
}

declare module 'smalldash/src/string/percent-string' {
  declare module.exports: any;
}

declare module 'smalldash/src/string/percent' {
  declare module.exports: any;
}

declare module 'smalldash/src/string/pixel-string' {
  declare module.exports: any;
}

declare module 'smalldash/src/string/sentence-to-camel' {
  declare module.exports: any;
}

declare module 'smalldash/src/string/sentence-to-kebab' {
  declare module.exports: any;
}

declare module 'smalldash/src/string/sentence-to-snake' {
  declare module.exports: any;
}

declare module 'smalldash/src/string/sentence-to-title' {
  declare module.exports: any;
}

declare module 'smalldash/src/string/sentence-to' {
  declare module.exports: any;
}

declare module 'smalldash/src/string/snake-to-camel' {
  declare module.exports: any;
}

declare module 'smalldash/src/string/snake-to-kebab' {
  declare module.exports: any;
}

declare module 'smalldash/src/string/snake-to-sentence' {
  declare module.exports: any;
}

declare module 'smalldash/src/string/snake-to' {
  declare module.exports: any;
}

declare module 'smalldash/src/string/time-string' {
  declare module.exports: any;
}

declare module 'smalldash/src/string/to-camel' {
  declare module.exports: any;
}

declare module 'smalldash/src/string/to-pascal' {
  declare module.exports: any;
}

declare module 'smalldash/src/string/types' {
  declare module.exports: any;
}

declare module 'smalldash/src/string/unit-string' {
  declare module.exports: any;
}

declare module 'smalldash/src/string/validate-decimal' {
  declare module.exports: any;
}

declare module 'smalldash/src/string/validate-hexadecimal' {
  declare module.exports: any;
}

declare module 'smalldash/src/string/validate-letter-string' {
  declare module.exports: any;
}

declare module 'smalldash/src/string/validate-number' {
  declare module.exports: any;
}

// Filename aliases
declare module 'smalldash/__tests__/module.test.js' {
  declare module.exports: $Exports<'smalldash/__tests__/module.test'>;
}
declare module 'smalldash/babel.config.js' {
  declare module.exports: $Exports<'smalldash/babel.config'>;
}
declare module 'smalldash/build/smalldash.cjs.js' {
  declare module.exports: $Exports<'smalldash/build/smalldash.cjs'>;
}
declare module 'smalldash/build/smalldash.esm.js' {
  declare module.exports: $Exports<'smalldash/build/smalldash.esm'>;
}
declare module 'smalldash/rollup.config.js' {
  declare module.exports: $Exports<'smalldash/rollup.config'>;
}
declare module 'smalldash/scripts/create-index.js' {
  declare module.exports: $Exports<'smalldash/scripts/create-index'>;
}
declare module 'smalldash/src/array/__tests__/fill-from.test.js' {
  declare module.exports: $Exports<'smalldash/src/array/__tests__/fill-from.test'>;
}
declare module 'smalldash/src/array/__tests__/fill-with.test.js' {
  declare module.exports: $Exports<'smalldash/src/array/__tests__/fill-with.test'>;
}
declare module 'smalldash/src/array/__tests__/uniq.test.js' {
  declare module.exports: $Exports<'smalldash/src/array/__tests__/uniq.test'>;
}
declare module 'smalldash/src/array/fill-from.js' {
  declare module.exports: $Exports<'smalldash/src/array/fill-from'>;
}
declare module 'smalldash/src/array/fill-with.js' {
  declare module.exports: $Exports<'smalldash/src/array/fill-with'>;
}
declare module 'smalldash/src/array/index.js' {
  declare module.exports: $Exports<'smalldash/src/array/index'>;
}
declare module 'smalldash/src/array/object-to-array.js' {
  declare module.exports: $Exports<'smalldash/src/array/object-to-array'>;
}
declare module 'smalldash/src/array/types.js' {
  declare module.exports: $Exports<'smalldash/src/array/types'>;
}
declare module 'smalldash/src/array/uniq.js' {
  declare module.exports: $Exports<'smalldash/src/array/uniq'>;
}
declare module 'smalldash/src/async/__tests__/compose-async.test.js' {
  declare module.exports: $Exports<'smalldash/src/async/__tests__/compose-async.test'>;
}
declare module 'smalldash/src/async/__tests__/debounce.test.js' {
  declare module.exports: $Exports<'smalldash/src/async/__tests__/debounce.test'>;
}
declare module 'smalldash/src/async/__tests__/pipe-async.test.js' {
  declare module.exports: $Exports<'smalldash/src/async/__tests__/pipe-async.test'>;
}
declare module 'smalldash/src/async/compose-async.js' {
  declare module.exports: $Exports<'smalldash/src/async/compose-async'>;
}
declare module 'smalldash/src/async/debounce.js' {
  declare module.exports: $Exports<'smalldash/src/async/debounce'>;
}
declare module 'smalldash/src/async/index.js' {
  declare module.exports: $Exports<'smalldash/src/async/index'>;
}
declare module 'smalldash/src/async/pipe-async.js' {
  declare module.exports: $Exports<'smalldash/src/async/pipe-async'>;
}
declare module 'smalldash/src/async/throttle.js' {
  declare module.exports: $Exports<'smalldash/src/async/throttle'>;
}
declare module 'smalldash/src/async/types.js' {
  declare module.exports: $Exports<'smalldash/src/async/types'>;
}
declare module 'smalldash/src/functional/__tests__/filter.test.js' {
  declare module.exports: $Exports<'smalldash/src/functional/__tests__/filter.test'>;
}
declare module 'smalldash/src/functional/__tests__/map-left.test.js' {
  declare module.exports: $Exports<'smalldash/src/functional/__tests__/map-left.test'>;
}
declare module 'smalldash/src/functional/__tests__/map-right.test.js' {
  declare module.exports: $Exports<'smalldash/src/functional/__tests__/map-right.test'>;
}
declare module 'smalldash/src/functional/__tests__/map.test.js' {
  declare module.exports: $Exports<'smalldash/src/functional/__tests__/map.test'>;
}
declare module 'smalldash/src/functional/__tests__/side-effects.test.js' {
  declare module.exports: $Exports<'smalldash/src/functional/__tests__/side-effects.test'>;
}
declare module 'smalldash/src/functional/compose.js' {
  declare module.exports: $Exports<'smalldash/src/functional/compose'>;
}
declare module 'smalldash/src/functional/create-array-method-mutable.js' {
  declare module.exports: $Exports<'smalldash/src/functional/create-array-method-mutable'>;
}
declare module 'smalldash/src/functional/create-array-method.js' {
  declare module.exports: $Exports<'smalldash/src/functional/create-array-method'>;
}
declare module 'smalldash/src/functional/filter-left.js' {
  declare module.exports: $Exports<'smalldash/src/functional/filter-left'>;
}
declare module 'smalldash/src/functional/filter-right.js' {
  declare module.exports: $Exports<'smalldash/src/functional/filter-right'>;
}
declare module 'smalldash/src/functional/filter.js' {
  declare module.exports: $Exports<'smalldash/src/functional/filter'>;
}
declare module 'smalldash/src/functional/index.js' {
  declare module.exports: $Exports<'smalldash/src/functional/index'>;
}
declare module 'smalldash/src/functional/map-left.js' {
  declare module.exports: $Exports<'smalldash/src/functional/map-left'>;
}
declare module 'smalldash/src/functional/map-right.js' {
  declare module.exports: $Exports<'smalldash/src/functional/map-right'>;
}
declare module 'smalldash/src/functional/map.js' {
  declare module.exports: $Exports<'smalldash/src/functional/map'>;
}
declare module 'smalldash/src/functional/pipe.js' {
  declare module.exports: $Exports<'smalldash/src/functional/pipe'>;
}
declare module 'smalldash/src/functional/side-effects.js' {
  declare module.exports: $Exports<'smalldash/src/functional/side-effects'>;
}
declare module 'smalldash/src/functional/types.js' {
  declare module.exports: $Exports<'smalldash/src/functional/types'>;
}
declare module 'smalldash/src/index.js' {
  declare module.exports: $Exports<'smalldash/src/index'>;
}
declare module 'smalldash/src/object/__tests__/equals.performance.test.js' {
  declare module.exports: $Exports<'smalldash/src/object/__tests__/equals.performance.test'>;
}
declare module 'smalldash/src/object/__tests__/equals.test.js' {
  declare module.exports: $Exports<'smalldash/src/object/__tests__/equals.test'>;
}
declare module 'smalldash/src/object/equals.js' {
  declare module.exports: $Exports<'smalldash/src/object/equals'>;
}
declare module 'smalldash/src/object/index.js' {
  declare module.exports: $Exports<'smalldash/src/object/index'>;
}
declare module 'smalldash/src/object/types.js' {
  declare module.exports: $Exports<'smalldash/src/object/types'>;
}
declare module 'smalldash/src/primitives/__tests__/arrayish.test.js' {
  declare module.exports: $Exports<'smalldash/src/primitives/__tests__/arrayish.test'>;
}
declare module 'smalldash/src/primitives/__tests__/nullish.test.js' {
  declare module.exports: $Exports<'smalldash/src/primitives/__tests__/nullish.test'>;
}
declare module 'smalldash/src/primitives/__tests__/numberish.test.js' {
  declare module.exports: $Exports<'smalldash/src/primitives/__tests__/numberish.test'>;
}
declare module 'smalldash/src/primitives/__tests__/objectish.test.js' {
  declare module.exports: $Exports<'smalldash/src/primitives/__tests__/objectish.test'>;
}
declare module 'smalldash/src/primitives/__tests__/stringish.test.js' {
  declare module.exports: $Exports<'smalldash/src/primitives/__tests__/stringish.test'>;
}
declare module 'smalldash/src/primitives/arrayish.js' {
  declare module.exports: $Exports<'smalldash/src/primitives/arrayish'>;
}
declare module 'smalldash/src/primitives/index.js' {
  declare module.exports: $Exports<'smalldash/src/primitives/index'>;
}
declare module 'smalldash/src/primitives/nullish.js' {
  declare module.exports: $Exports<'smalldash/src/primitives/nullish'>;
}
declare module 'smalldash/src/primitives/numberish.js' {
  declare module.exports: $Exports<'smalldash/src/primitives/numberish'>;
}
declare module 'smalldash/src/primitives/objectish.js' {
  declare module.exports: $Exports<'smalldash/src/primitives/objectish'>;
}
declare module 'smalldash/src/primitives/stringish.js' {
  declare module.exports: $Exports<'smalldash/src/primitives/stringish'>;
}
declare module 'smalldash/src/primitives/types.js' {
  declare module.exports: $Exports<'smalldash/src/primitives/types'>;
}
declare module 'smalldash/src/string/__tests__/camel.test.js' {
  declare module.exports: $Exports<'smalldash/src/string/__tests__/camel.test'>;
}
declare module 'smalldash/src/string/__tests__/capitalize.test.js' {
  declare module.exports: $Exports<'smalldash/src/string/__tests__/capitalize.test'>;
}
declare module 'smalldash/src/string/__tests__/currency-string.test.js' {
  declare module.exports: $Exports<'smalldash/src/string/__tests__/currency-string.test'>;
}
declare module 'smalldash/src/string/__tests__/is-lower-case.test.js' {
  declare module.exports: $Exports<'smalldash/src/string/__tests__/is-lower-case.test'>;
}
declare module 'smalldash/src/string/__tests__/is-upper-case.test.js' {
  declare module.exports: $Exports<'smalldash/src/string/__tests__/is-upper-case.test'>;
}
declare module 'smalldash/src/string/__tests__/kebab.test.js' {
  declare module.exports: $Exports<'smalldash/src/string/__tests__/kebab.test'>;
}
declare module 'smalldash/src/string/__tests__/pad-digits.test.js' {
  declare module.exports: $Exports<'smalldash/src/string/__tests__/pad-digits.test'>;
}
declare module 'smalldash/src/string/__tests__/percent.test.js' {
  declare module.exports: $Exports<'smalldash/src/string/__tests__/percent.test'>;
}
declare module 'smalldash/src/string/__tests__/validate-decimal.test.js' {
  declare module.exports: $Exports<'smalldash/src/string/__tests__/validate-decimal.test'>;
}
declare module 'smalldash/src/string/accept-strings.js' {
  declare module.exports: $Exports<'smalldash/src/string/accept-strings'>;
}
declare module 'smalldash/src/string/camel-to-kebab.js' {
  declare module.exports: $Exports<'smalldash/src/string/camel-to-kebab'>;
}
declare module 'smalldash/src/string/camel-to-pascal.js' {
  declare module.exports: $Exports<'smalldash/src/string/camel-to-pascal'>;
}
declare module 'smalldash/src/string/camel-to-sentence.js' {
  declare module.exports: $Exports<'smalldash/src/string/camel-to-sentence'>;
}
declare module 'smalldash/src/string/camel-to-snake.js' {
  declare module.exports: $Exports<'smalldash/src/string/camel-to-snake'>;
}
declare module 'smalldash/src/string/camel-to-title.js' {
  declare module.exports: $Exports<'smalldash/src/string/camel-to-title'>;
}
declare module 'smalldash/src/string/camel-to.js' {
  declare module.exports: $Exports<'smalldash/src/string/camel-to'>;
}
declare module 'smalldash/src/string/capitalize.js' {
  declare module.exports: $Exports<'smalldash/src/string/capitalize'>;
}
declare module 'smalldash/src/string/case-to-case.js' {
  declare module.exports: $Exports<'smalldash/src/string/case-to-case'>;
}
declare module 'smalldash/src/string/currency-string.js' {
  declare module.exports: $Exports<'smalldash/src/string/currency-string'>;
}
declare module 'smalldash/src/string/dollar-string.js' {
  declare module.exports: $Exports<'smalldash/src/string/dollar-string'>;
}
declare module 'smalldash/src/string/index.js' {
  declare module.exports: $Exports<'smalldash/src/string/index'>;
}
declare module 'smalldash/src/string/is-lower-case.js' {
  declare module.exports: $Exports<'smalldash/src/string/is-lower-case'>;
}
declare module 'smalldash/src/string/is-upper-case.js' {
  declare module.exports: $Exports<'smalldash/src/string/is-upper-case'>;
}
declare module 'smalldash/src/string/kebab-to-camel.js' {
  declare module.exports: $Exports<'smalldash/src/string/kebab-to-camel'>;
}
declare module 'smalldash/src/string/kebab-to-sentence.js' {
  declare module.exports: $Exports<'smalldash/src/string/kebab-to-sentence'>;
}
declare module 'smalldash/src/string/kebab-to-snake.js' {
  declare module.exports: $Exports<'smalldash/src/string/kebab-to-snake'>;
}
declare module 'smalldash/src/string/kebab-to-title.js' {
  declare module.exports: $Exports<'smalldash/src/string/kebab-to-title'>;
}
declare module 'smalldash/src/string/kebab-to.js' {
  declare module.exports: $Exports<'smalldash/src/string/kebab-to'>;
}
declare module 'smalldash/src/string/pad-digits.js' {
  declare module.exports: $Exports<'smalldash/src/string/pad-digits'>;
}
declare module 'smalldash/src/string/pad-zero.js' {
  declare module.exports: $Exports<'smalldash/src/string/pad-zero'>;
}
declare module 'smalldash/src/string/percent-string.js' {
  declare module.exports: $Exports<'smalldash/src/string/percent-string'>;
}
declare module 'smalldash/src/string/percent.js' {
  declare module.exports: $Exports<'smalldash/src/string/percent'>;
}
declare module 'smalldash/src/string/pixel-string.js' {
  declare module.exports: $Exports<'smalldash/src/string/pixel-string'>;
}
declare module 'smalldash/src/string/sentence-to-camel.js' {
  declare module.exports: $Exports<'smalldash/src/string/sentence-to-camel'>;
}
declare module 'smalldash/src/string/sentence-to-kebab.js' {
  declare module.exports: $Exports<'smalldash/src/string/sentence-to-kebab'>;
}
declare module 'smalldash/src/string/sentence-to-snake.js' {
  declare module.exports: $Exports<'smalldash/src/string/sentence-to-snake'>;
}
declare module 'smalldash/src/string/sentence-to-title.js' {
  declare module.exports: $Exports<'smalldash/src/string/sentence-to-title'>;
}
declare module 'smalldash/src/string/sentence-to.js' {
  declare module.exports: $Exports<'smalldash/src/string/sentence-to'>;
}
declare module 'smalldash/src/string/snake-to-camel.js' {
  declare module.exports: $Exports<'smalldash/src/string/snake-to-camel'>;
}
declare module 'smalldash/src/string/snake-to-kebab.js' {
  declare module.exports: $Exports<'smalldash/src/string/snake-to-kebab'>;
}
declare module 'smalldash/src/string/snake-to-sentence.js' {
  declare module.exports: $Exports<'smalldash/src/string/snake-to-sentence'>;
}
declare module 'smalldash/src/string/snake-to.js' {
  declare module.exports: $Exports<'smalldash/src/string/snake-to'>;
}
declare module 'smalldash/src/string/time-string.js' {
  declare module.exports: $Exports<'smalldash/src/string/time-string'>;
}
declare module 'smalldash/src/string/to-camel.js' {
  declare module.exports: $Exports<'smalldash/src/string/to-camel'>;
}
declare module 'smalldash/src/string/to-pascal.js' {
  declare module.exports: $Exports<'smalldash/src/string/to-pascal'>;
}
declare module 'smalldash/src/string/types.js' {
  declare module.exports: $Exports<'smalldash/src/string/types'>;
}
declare module 'smalldash/src/string/unit-string.js' {
  declare module.exports: $Exports<'smalldash/src/string/unit-string'>;
}
declare module 'smalldash/src/string/validate-decimal.js' {
  declare module.exports: $Exports<'smalldash/src/string/validate-decimal'>;
}
declare module 'smalldash/src/string/validate-hexadecimal.js' {
  declare module.exports: $Exports<'smalldash/src/string/validate-hexadecimal'>;
}
declare module 'smalldash/src/string/validate-letter-string.js' {
  declare module.exports: $Exports<'smalldash/src/string/validate-letter-string'>;
}
declare module 'smalldash/src/string/validate-number.js' {
  declare module.exports: $Exports<'smalldash/src/string/validate-number'>;
}
