// flow-typed signature: 309b45999e9a3558d0ed5275104630ea
// flow-typed version: <<STUB>>/@artetexture/server-middleware_v^0.0.1/flow_v0.83.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   '@artetexture/server-middleware'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module '@artetexture/server-middleware' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module '@artetexture/server-middleware/babel.config' {
  declare module.exports: any;
}

declare module '@artetexture/server-middleware/build/index.cjs' {
  declare module.exports: any;
}

declare module '@artetexture/server-middleware/build/index.esm' {
  declare module.exports: any;
}

declare module '@artetexture/server-middleware/flow-typed/npm/@babel/runtime_vx.x.x' {
  declare module.exports: any;
}

declare module '@artetexture/server-middleware/flow-typed/npm/body-parser_v1.x.x' {
  declare module.exports: any;
}

declare module '@artetexture/server-middleware/flow-typed/npm/cors_v2.x.x' {
  declare module.exports: any;
}

declare module '@artetexture/server-middleware/flow-typed/npm/express_v4.16.x' {
  declare module.exports: any;
}

declare module '@artetexture/server-middleware/flow-typed/npm/smalldash_vx.x.x' {
  declare module.exports: any;
}

declare module '@artetexture/server-middleware/rollup.config' {
  declare module.exports: any;
}

declare module '@artetexture/server-middleware/src/auth' {
  declare module.exports: any;
}

declare module '@artetexture/server-middleware/src/body-parser' {
  declare module.exports: any;
}

declare module '@artetexture/server-middleware/src/cors' {
  declare module.exports: any;
}

declare module '@artetexture/server-middleware/src/domain' {
  declare module.exports: any;
}

declare module '@artetexture/server-middleware/src/index' {
  declare module.exports: any;
}

declare module '@artetexture/server-middleware/src/is-dev' {
  declare module.exports: any;
}

declare module '@artetexture/server-middleware/src/log' {
  declare module.exports: any;
}

declare module '@artetexture/server-middleware/src/response-headers' {
  declare module.exports: any;
}

declare module '@artetexture/server-middleware/src/secure' {
  declare module.exports: any;
}

declare module '@artetexture/server-middleware/src/validate-body' {
  declare module.exports: any;
}

// Filename aliases
declare module '@artetexture/server-middleware/babel.config.js' {
  declare module.exports: $Exports<'@artetexture/server-middleware/babel.config'>;
}
declare module '@artetexture/server-middleware/build/index.cjs.js' {
  declare module.exports: $Exports<'@artetexture/server-middleware/build/index.cjs'>;
}
declare module '@artetexture/server-middleware/build/index.esm.js' {
  declare module.exports: $Exports<'@artetexture/server-middleware/build/index.esm'>;
}
declare module '@artetexture/server-middleware/flow-typed/npm/@babel/runtime_vx.x.x.js' {
  declare module.exports: $Exports<'@artetexture/server-middleware/flow-typed/npm/@babel/runtime_vx.x.x'>;
}
declare module '@artetexture/server-middleware/flow-typed/npm/body-parser_v1.x.x.js' {
  declare module.exports: $Exports<'@artetexture/server-middleware/flow-typed/npm/body-parser_v1.x.x'>;
}
declare module '@artetexture/server-middleware/flow-typed/npm/cors_v2.x.x.js' {
  declare module.exports: $Exports<'@artetexture/server-middleware/flow-typed/npm/cors_v2.x.x'>;
}
declare module '@artetexture/server-middleware/flow-typed/npm/express_v4.16.x.js' {
  declare module.exports: $Exports<'@artetexture/server-middleware/flow-typed/npm/express_v4.16.x'>;
}
declare module '@artetexture/server-middleware/flow-typed/npm/smalldash_vx.x.x.js' {
  declare module.exports: $Exports<'@artetexture/server-middleware/flow-typed/npm/smalldash_vx.x.x'>;
}
declare module '@artetexture/server-middleware/rollup.config.js' {
  declare module.exports: $Exports<'@artetexture/server-middleware/rollup.config'>;
}
declare module '@artetexture/server-middleware/src/auth.js' {
  declare module.exports: $Exports<'@artetexture/server-middleware/src/auth'>;
}
declare module '@artetexture/server-middleware/src/body-parser.js' {
  declare module.exports: $Exports<'@artetexture/server-middleware/src/body-parser'>;
}
declare module '@artetexture/server-middleware/src/cors.js' {
  declare module.exports: $Exports<'@artetexture/server-middleware/src/cors'>;
}
declare module '@artetexture/server-middleware/src/domain.js' {
  declare module.exports: $Exports<'@artetexture/server-middleware/src/domain'>;
}
declare module '@artetexture/server-middleware/src/index.js' {
  declare module.exports: $Exports<'@artetexture/server-middleware/src/index'>;
}
declare module '@artetexture/server-middleware/src/is-dev.js' {
  declare module.exports: $Exports<'@artetexture/server-middleware/src/is-dev'>;
}
declare module '@artetexture/server-middleware/src/log.js' {
  declare module.exports: $Exports<'@artetexture/server-middleware/src/log'>;
}
declare module '@artetexture/server-middleware/src/response-headers.js' {
  declare module.exports: $Exports<'@artetexture/server-middleware/src/response-headers'>;
}
declare module '@artetexture/server-middleware/src/secure.js' {
  declare module.exports: $Exports<'@artetexture/server-middleware/src/secure'>;
}
declare module '@artetexture/server-middleware/src/validate-body.js' {
  declare module.exports: $Exports<'@artetexture/server-middleware/src/validate-body'>;
}
