// flow-typed signature: 5afcf1a37cced4af80e914b4ad271639
// flow-typed version: <<STUB>>/serverless-plugin-monorepo_v^0.4.0/flow_v0.83.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'serverless-plugin-monorepo'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'serverless-plugin-monorepo' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */


// Filename aliases
declare module 'serverless-plugin-monorepo/index' {
  declare module.exports: $Exports<'serverless-plugin-monorepo'>;
}
declare module 'serverless-plugin-monorepo/index.js' {
  declare module.exports: $Exports<'serverless-plugin-monorepo'>;
}
