sudo:           false
language:       node_js
node_js:
  - 10.13.0
branches:
  only:
    - staging
    - master
cache:
  bundler:      true
  directories:
    - node_modules
    - packages/web/public
    - packages/web/.cache
    - packages/checkout-objects/node_modules
    - packages/data-objects/node_modules
    - packages/gatsby-source-wordpress/node_modules
    - packages/mail-server/node_modules
    - packages/server-env/node_modules
    - packages/server-middleware/node_modules
    - packages/templates/node_modules
    - packages/web/node_modules
  timeout:      1000
before_install:
  - curl -o- -L https://yarnpkg.com/install.sh | bash -s -- --version 1.12.3
  - export PATH=$HOME/.yarn/bin:$PATH
script:
  - yarn bootstrap
  - node scripts/deploy
env:
  global:
    - STAGE=staging
    - GATSBY_BRAINTREE_SERVER_STAGING=$GATSBY_BRAINTREE_SERVER_STAGING
    - GATSBY_MAIL_SERVER_STAGING=$GATSBY_MAIL_SERVER_STAGING
    - GATSBY_API_KEY_STAGING=$GATSBY_API_KEY_STAGING
    - GATSBY_BRAINTREE_SERVER_PRODUCTION=$GATSBY_BRAINTREE_SERVER_PRODUCTION
    - GATSBY_MAIL_SERVER_PRODUCTION=$GATSBY_MAIL_SERVER_PRODUCTION
    - GATSBY_API_KEY_PRODUCTION=$GATSBY_API_KEY_PRODUCTION
    - ROOT_DOMAIN_STAGING=$ROOT_DOMAIN_STAGING
    - API_KEY_STAGING=$API_KEY_STAGING
    - MAIL_DOMAIN_STAGING=$MAIL_DOMAIN_STAGING
    - MAILGUN_DOMAIN_STAGING=$MAILGUN_DOMAIN_STAGING
    - MAILGUN_API_KEY_STAGING=$MAILGUN_API_KEY_STAGING
    - EMAIL_RECIPIENT_STAGING=$EMAIL_RECIPIENT_STAGING
    - CHECKOUT_DOMAIN_STAGING=$CHECKOUT_DOMAIN_STAGING
    - BRAINTREE_MERCHANT_ID_STAGING=$BRAINTREE_MERCHANT_ID_STAGING
    - BRAINTREE_PUBLIC_KEY_STAGING=$BRAINTREE_PUBLIC_KEY_STAGING
    - BRAINTREE_PRIVATE_KEY_STAGING=$BRAINTREE_PRIVATE_KEY_STAGING
    - ROOT_DOMAIN_PRODUCTION=$ROOT_DOMAIN_PRODUCTION
    - API_KEY_PRODUCTION=$API_KEY_PRODUCTION
    - MAIL_DOMAIN_PRODUCTION=$MAIL_DOMAIN_PRODUCTION
    - MAILGUN_DOMAIN_PRODUCTION=$MAILGUN_DOMAIN_PRODUCTION
    - MAILGUN_API_KEY_PRODUCTION=$MAILGUN_API_KEY_PRODUCTION
    - EMAIL_RECIPIENT_PRODUCTION=$EMAIL_RECIPIENT_PRODUCTION
    - CHECKOUT_DOMAIN_PRODUCTION=$CHECKOUT_DOMAIN_PRODUCTION
    - BRAINTREE_MERCHANT_ID_PRODUCTION=$BRAINTREE_MERCHANT_ID_PRODUCTION
    - BRAINTREE_PUBLIC_KEY_PRODUCTION=$BRAINTREE_PUBLIC_KEY_PRODUCTION
    - BRAINTREE_PRIVATE_KEY_PRODUCTION=$BRAINTREE_PRIVATE_KEY_PRODUCTION
