---
sudo:            false

language:        node_js

node_js:
  - stable

branches:
  only:
  - travis

cache:
  directories:
    - node_modules
    - packages/web/build
    - packages/web/.cache

before_install:
  - curl -o- -L https://yarnpkg.com/install.sh | bash -s -- --version 1.12.3
  - export PATH=$HOME/.yarn/bin:$PATH
  
script:
  - yarn bootstrap
  - yarn build
