---
sudo:            false

language:        node_js

node_js:
  - 10.13.0

branches:
  only:
  - staging

cache:
  bundler:       true
  directories:
    - node_modules
    - packages/web/public
    - packages/web/.cache
    - packages/checkout-objects/node_modules
    - packages/data-objects/node_modules
    - packages/gatsby-source-wordpress/node_modules
    - packages/mail-server/node_modules
    - packages/server-env/node_modules
    - packages/server-middleware/node_modules
    - packages/templates/node_modules
    - packages/web/node_modules

before_install:
  - curl -o- -L https://yarnpkg.com/install.sh | bash -s -- --version 1.12.3
  - export PATH=$HOME/.yarn/bin:$PATH

script:
  - export STAGE=$(if [ "$TRAVIS_PULL_REQUEST" == "false" ]; then echo $TRAVIS_BRANCH; else echo $TRAVIS_PULL_REQUEST_BRANCH; fi)
  - echo "TRAVIS_BRANCH=$TRAVIS_BRANCH, PR=$PR, STAGE=$STAGE"
  - yarn bootstrap
  - yarn stage
