sudo: false
language: node_js
node_js:
- 10.13.0
branches:
  only:
  - staging
cache:
  bundler: true
  directories:
  - node_modules
  - packages/web/public
  - packages/web/.cache
  - packages/checkout-objects/node_modules
  - packages/data-objects/node_modules
  - packages/gatsby-source-wordpress/node_modules
  - packages/mail-server/node_modules
  - packages/server-env/node_modules
  - packages/server-middleware/node_modules
  - packages/templates/node_modules
  - packages/web/node_modules
  timeout: 1000
before_install:
- curl -o- -L https://yarnpkg.com/install.sh | bash -s -- --version 1.12.3
- export PATH=$HOME/.yarn/bin:$PATH
script:
- export STAGE=$(if [ "$TRAVIS_PULL_REQUEST" == "false" ]; then echo $TRAVIS_BRANCH;
  else echo $TRAVIS_PULL_REQUEST_BRANCH; fi)
- echo "TRAVIS_BRANCH=$TRAVIS_BRANCH, PR=$PR, STAGE=$STAGE"
- yarn bootstrap
- yarn stage
env:
  global:
  - secure: bgLYEGUis+qmt9XjaGriQoNWsiv4Sy+17fIRp5EHlN/sfDMjNyiuoFZgIAmk1xPI2ZhLivZd/HZsXOuhnw2LrUTFpmPErd2xdud+V6vMwaQZPOHqUZEpyPy0wAn/q0zw6ICbuBCsVQ6DHufEqaWMMFT1kNxDPUPsEjcVXanOPmeh3WnzLo0crz1+kq9KJmpWzHfrcSJhm3Mdn5AqIq2RHVhajMX0ru3XLR0ulcuMaZfOLi9/2THaIF+6YgcbqFn2TGbDPgw4UhXs2KDvhP0zoj4iq2fNu52pK5gDNONq1KJYaAfW9wBUBEKs5D8FRXCoIadzF4ByVGloDro6ZzZ/v0mcMrGtGRtAFQ0OIn3PudshrNBK/yrBv2mdl9rpGgcSofSXGqbV2XGuy5Hyw/zhrIufl3+0i3VokkwsefwNP0zxFJpoBUsa5c4P4Yyw4iGNwawVIzrSt+1yR0GQA2Xb0FsPH30j/Vd5ySo0LcF7X+szaJsFnWwuzcUxbAJlpjrFMHlRzDDSRT8oNVwtdmJc24S/ecoh8lMLYfcqTDRbZg7mflmoLPM9+yTZzVRkcMVHOUzcxK1BPzwaiXfV2l5c4i7X0+TzYj7O/0UCurRzIxlxidfODMNv4B6KCeiy3TeIER+JKGF7eWUKMXFEV4BhG3YiU7iQggmQNwBtG2SqyRE=
  - secure: aXo6FWE1eKrjQkk3nkFIXiwV73vm976Vs/OdIkldcVegzhIdOWitou2hk2zLpKiLT60L05uEcozzyGQsV1I2Vb7geefsms14CRZz0FT+AStI7IekPYajb1wOO40PBvkf0JXdimKa2W4vsXFzI4+zevFGDdbD/wDXeXsBo4lORn6gODDVmL4cubNoEIIzuOhT/UmzbfM9UfHN8oZk9Ze4KAxGaS+W3KDT9WaJkuN5/0pi5RLzOZYVEOeeR+TbkSiVz5Orq+Ss6m/b+yFuTXTMoC/0NRfv703KNpSfXYYi7OOZoVrMJNF99M0nc2/7rMS94YarF0T9eh32yw+3yuZ66cptAnTxl9kiaX6yZecaITEwiiwUqsQE/axUNvyIuECn+kQO8ipl86MaB3KC05Es88xnWZmqTCiSlqkcO/FMHEUF5H/rso0t1eHl5i8jk8TvvKtRe+9PaxJ79jpjCm9NRC9jLZFOUGLuotoI441jRiEnAI2WKmkmUVJn0XAeKtmAp/GeKi/HR8asM44Wx/jMUlzq7xyP6y2+f7q0hgNl7UfWMucbksP3t96jVVBng3PoPxjfmcdyFgw3b6NNESBfDEiIJfz9SLr940h4OVHtG4aD5wLFT9j2Af6infa5v0qUdMJtPRrdIWLMK2TEGlyM18mXU++G9f7cNWMmv88rSxo=
  - secure: ahF1CqenE91Z8hw5dXshuI1aBVs4YKxkac5LiDhn5GeEYLoWVLerx9XJ9IXtguodSNga0ikICSHUaHVMAuJmnKdJOgO2/B+v5flfIzamBVrJe2UlbPY5mJUEc/VvYcsLz6u7lave4lL73FrjhqstV0zhJPZz2Hlg8z+eoONGSICmMrnmrf8nvAbVc5Daam8JWMdFWXAcOR2CN7HufuTfSxYKpgWpDyLZSqcdREfxpWjCRaZ+nWA8KX7LbfWBgSwXjPpLGLe7WSCL5VuGSNUP1arhmXX9o1zmQnWjuDboAPS9ymloz4q6kJTovJTVF46i88BbcG694lFsDyds2AmgSoNYRBrC/K3F0EAD9VlzSz2Dd7UgM+O01BKNk098dDRBAdyaqwaBr0TSc5AqC+6nUkDk8b4fnYqK2hxCRMyJxg8YoBSYX+a6MrqY2rl36K095NF2qH0oRXP1IiAXuNzukfEpMldpKd9rWl96WljFLanYvdI5hgNvRcbFjrNGLQsWOeroHzD0dBLTFilTO94B74arx6eAThPNCkALRGN9S7p8eMG8lNQdV9W8nmnupdytSFY1w1GjMb6R5LKLRyEIq77VGkszK6XPlU7e1kNHIltkFcB090x6rYGZJPgTHtiYry5eT/+4d8uldPyGRfgOIHLC2Y1PYqP763cTN3CZTUA=
