---
sudo:            false

language:        node_js

node_js:
  - 10.13.0

branches:
  only:
  - travis

cache:
  bundler:       true
  directories:
    - node_modules
    - packages/web/public
    - packages/web/.cache
    - packages/**/node_modules

before_install:
  - curl -o- -L https://yarnpkg.com/install.sh | bash -s -- --version 1.12.3
  - export PATH=$HOME/.yarn/bin:$PATH

script:
  - yarn bootstrap
  - yarn stage
  - yarn build-web

deploy:
  provider:      s3
  bucket:        byalejandra.com
  acl:           public_read
  skip_cleanup:  true
  local_dir:     packages/web/public
