sudo: false
language: node_js
node_js:
- 10.13.0
branches:
  only:
  - staging
cache:
  bundler: true
  directories:
  - node_modules
  - packages/web/public
  - packages/web/.cache
  - packages/checkout-objects/node_modules
  - packages/data-objects/node_modules
  - packages/gatsby-source-wordpress/node_modules
  - packages/mail-server/node_modules
  - packages/server-env/node_modules
  - packages/server-middleware/node_modules
  - packages/templates/node_modules
  - packages/web/node_modules
  timeout: 1000
before_install:
- curl -o- -L https://yarnpkg.com/install.sh | bash -s -- --version 1.12.3
- export PATH=$HOME/.yarn/bin:$PATH
script:
- yarn bootstrap
- yarn stage
env:
  global:
  - STAGE=staging
  - secure: Z0tpka/zYHlFxqeqfehg+3PBHvJyjV+CnHeyKXFiwB0ijZSV0iq5opXHbtn65ccxU1HjUYjdNvOA1lEfXcbkdbIdasSnsW1fagM2leuDcue7Puvkg+Nf21mc5f6YoAjx60WjaDMDS1WtyS6iukJ739FW/FzWtwsdeaDpYVi+RPJ00pm9xh9zs/qagY+bVVUHdgypBo5olCxkpsxafLcZatiCydHrhNA67KlXooKjsU/fwuA7VO8Yjjr09tuBqupnK8wmAPinLcep2zxUJ8OLpmVXuoBoia8gS7bj/dl3ci6wnfuIZQJ4ZTfzNRSHujYFBqlesKccZSpRjVOXTAEcRYp/tQSJD5UqJUIhyr/FL4X8lOr4Lx0BISK/EwfUe9X8heDL7hDlUDPXWBCe+98K7T90465CG86JTXk9SyD/J8AuWJ9qH/U/YHnlbY57M2Yocj7m0tXM4kOIGJ0YRbrDSRA4f+Xcw/A2nNwraqdkSRNMju6gZZharUY+FqJY1qW2k2iBASjceWE3s8ZHOaw/V5IapNJ4jr+lkqAoVANGDy4zppdFFsv4PUsgpy+qCZFNXqch0ierhAa7NSluTaPVVGCrCXBVSluvWs97jTP4WVhfmZIqXbvldAVWJsLExnv9IthbrPACOlv0r+l9zTw9JqUg29+apxwfuxpw6CpPHSg=
