[build]
  # subdirectory to publish from
  # base = "subdirectory"
  publish = "public/"
  command = "gatsby build"

[context.production]

  environment = { YARN_VERSION = "1.10.1", GATSBY_BRAINTREE_SERVER="http://localhost:3000" }

[context.staging]

  environment = { YARN_VERSION = "1.10.1", GATSBY_BRAINTREE_SERVER="http://localhost:3000" }
