[build]
  # subdirectory to publish from
  # base = "subdirectory"
  publish = "public/"
  command = "yarn run build-web"

[build.environment]
  YARN_VERSION = "1.10.1"

[context.production.environment]
  GATSBY_BRAINTREE_SERVER="http://localhost:3000"

[context.staging.environment]
  GATSBY_BRAINTREE_SERVER="http://localhost:3000"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
