[build]
  # subdirectory to publish from
  # base = "subdirectory"
  publish = "packages/web/public"
  command = "npm run build-web"

[build.environment]
  NODE_VERSION = "10.13.0"
  YARN_VERSION = "1.12.3"


[context.production.environment]
  GATSBY_BRAINTREE_SERVER="https://checkout--staging.byalejandradesign.com"
  GATSBY_MAIL_SERVER="https://mail--staging.byalejandradesign.com"
  STAGE="production"

[context.staging.environment]
  GATSBY_BRAINTREE_SERVER="https://checkout--staging.byalejandradesign.com"
  GATSBY_MAIL_SERVER="https://mail--staging.byalejandradesign.com"
  STAGE="staging"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
