# Javascript Node CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-javascript/ for more details
#
version: 2.1
jobs:
  # install dependencies and setup
  setup:
    working_directory: ~/byalejandradesign.com
    docker:
      - image: circleci/node:10.13-browsers
    steps:
      - checkout
      # install package managers
      - run:
          name: Install Global NPM Modules
          command: sudo npm install -g yarn
      # download and cache dependencies
      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "package.json" }}
      # install local dependencies
      - run:
          name: Install Local NPM Modules
          command: yarn && yarn bootstrap

  # run tests
  test:
    working_directory: ~/byalejandradesign.com
    docker:
      - image: circleci/node:10.13-browsers
    steps:
      - run: yarn test

  # build and deploy
  deploy:
    working_directory: ~/byalejandradesign.com
    docker:
      - image: circleci/node:10.13-browsers
    branches:
      only:
        - staging
        - master
    steps:
      # export branch variable
      - run:
          name: Setup Branch Variable
          command: echo $CIRCLE_BRANCH >> $BRANCH
      # build project
      - run:
          name: Build Project
          command: yarn package

  # cleanup and cache dependencies
  cleanup:
    working_directory: ~/byalejandradesign.com
    docker:
      - image: circleci/node:10.13-browsers
    steps:
      - save_cache:
          paths:
            - node_modules
            - /packages/*/node_modules
            - /packages/*/.cache
            - /packages/*/build
          key: v1-dependencies-{{ checksum "package.json" }}