/** @flow */
import normalizeDomain from './normalize-domain';

const env = {
  NODE_ENV: 'STAGE',
  STAGE: 'STAGE',
  ROOT_DOMAIN: normalizeDomain('ROOT_DOMAIN'),
  CHECKOUT_DOMAIN: normalizeDomain('CHECKOUT_DOMAIN'),
  MAIL_DOMAIN: normalizeDomain('MAIL_DOMAIN'),
  EMAIL_RECIPIENT: 'EMAIL_RECIPIENT',
  API_KEY: 'API_KEY',
  MAILGUN_DOMAIN: 'MAILGUN_DOMAIN',
  MAILGUN_API_KEY: 'MAILGUN_API_KEY',
  BRAINTREE_MERCHANT_ID: 'BRAINTREE_MERCHANT_ID',
  BRAINTREE_PUBLIC_KEY: 'BRAINTREE_PUBLIC_KEY',
  BRAINTREE_PRIVATE_KEY: 'BRAINTREE_PRIVATE_KEY',
};

export default env;
