// flow-typed signature: 022b31d46520642a466295a5760f741b
// flow-typed version: <<STUB>>/@njmyers/component-library_v^0.2.11/flow_v0.83.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   '@njmyers/component-library'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module '@njmyers/component-library' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module '@njmyers/component-library/babel.config' {
  declare module.exports: any;
}

declare module '@njmyers/component-library/build/components.cjs' {
  declare module.exports: any;
}

declare module '@njmyers/component-library/build/components.esm' {
  declare module.exports: any;
}

declare module '@njmyers/component-library/rollup.config' {
  declare module.exports: any;
}

declare module '@njmyers/component-library/scripts/docgen' {
  declare module.exports: any;
}

declare module '@njmyers/component-library/scripts/generate-markdown' {
  declare module.exports: any;
}

declare module '@njmyers/component-library/scripts/readme' {
  declare module.exports: any;
}

declare module '@njmyers/component-library/src/BEM/__tests__/BEM.integration.test' {
  declare module.exports: any;
}

declare module '@njmyers/component-library/src/BEM/__tests__/BEM.unit.test' {
  declare module.exports: any;
}

declare module '@njmyers/component-library/src/BEM/BEM' {
  declare module.exports: any;
}

declare module '@njmyers/component-library/src/BEM/index' {
  declare module.exports: any;
}

declare module '@njmyers/component-library/src/ErrorMessage/ErrorMessage' {
  declare module.exports: any;
}

declare module '@njmyers/component-library/src/ErrorMessage/index' {
  declare module.exports: any;
}

declare module '@njmyers/component-library/src/Form/__tests__/Input.test' {
  declare module.exports: any;
}

declare module '@njmyers/component-library/src/Form/index' {
  declare module.exports: any;
}

declare module '@njmyers/component-library/src/Form/Input' {
  declare module.exports: any;
}

declare module '@njmyers/component-library/src/Form/Select' {
  declare module.exports: any;
}

declare module '@njmyers/component-library/src/Form/Submit' {
  declare module.exports: any;
}

declare module '@njmyers/component-library/src/Form/TextArea' {
  declare module.exports: any;
}

declare module '@njmyers/component-library/src/Icon/Arrow' {
  declare module.exports: any;
}

declare module '@njmyers/component-library/src/Icon/Bag' {
  declare module.exports: any;
}

declare module '@njmyers/component-library/src/Icon/Caret' {
  declare module.exports: any;
}

declare module '@njmyers/component-library/src/Icon/Circle' {
  declare module.exports: any;
}

declare module '@njmyers/component-library/src/Icon/Cross' {
  declare module.exports: any;
}

declare module '@njmyers/component-library/src/Icon/Hamburger' {
  declare module.exports: any;
}

declare module '@njmyers/component-library/src/Icon/Icon' {
  declare module.exports: any;
}

declare module '@njmyers/component-library/src/Icon/index' {
  declare module.exports: any;
}

declare module '@njmyers/component-library/src/Icon/Minus' {
  declare module.exports: any;
}

declare module '@njmyers/component-library/src/Icon/Plus' {
  declare module.exports: any;
}

declare module '@njmyers/component-library/src/Icon/Ring' {
  declare module.exports: any;
}

declare module '@njmyers/component-library/src/Icon/RingSlash' {
  declare module.exports: any;
}

declare module '@njmyers/component-library/src/Icon/stories/icon.stories' {
  declare module.exports: any;
}

declare module '@njmyers/component-library/src/index' {
  declare module.exports: any;
}

declare module '@njmyers/component-library/src/LazyImage/index' {
  declare module.exports: any;
}

declare module '@njmyers/component-library/src/LazyImage/LazyImage' {
  declare module.exports: any;
}

declare module '@njmyers/component-library/src/LazyImage/stories/Changer' {
  declare module.exports: any;
}

declare module '@njmyers/component-library/src/LazyImage/stories/image.stories' {
  declare module.exports: any;
}

declare module '@njmyers/component-library/src/loadComponent/__tests__/loadComponent.test' {
  declare module.exports: any;
}

declare module '@njmyers/component-library/src/loadComponent/index' {
  declare module.exports: any;
}

declare module '@njmyers/component-library/src/loadComponent/loadComponent' {
  declare module.exports: any;
}

declare module '@njmyers/component-library/src/loadComponent/TestComponent' {
  declare module.exports: any;
}

declare module '@njmyers/component-library/src/Loading/index' {
  declare module.exports: any;
}

declare module '@njmyers/component-library/src/Loading/Loading' {
  declare module.exports: any;
}

declare module '@njmyers/component-library/src/Loading/stories/loading.stories' {
  declare module.exports: any;
}

declare module '@njmyers/component-library/src/Modal/index' {
  declare module.exports: any;
}

declare module '@njmyers/component-library/src/Modal/Modal' {
  declare module.exports: any;
}

declare module '@njmyers/component-library/src/Modal/ModalUnstyled' {
  declare module.exports: any;
}

declare module '@njmyers/component-library/src/Modal/stories/modal.stories' {
  declare module.exports: any;
}

declare module '@njmyers/component-library/src/Scratch/Headings' {
  declare module.exports: any;
}

declare module '@njmyers/component-library/src/Scratch/LoremIpsum' {
  declare module.exports: any;
}

declare module '@njmyers/component-library/src/SemiSticky/__tests__/SemiSticky.test' {
  declare module.exports: any;
}

declare module '@njmyers/component-library/src/SemiSticky/index' {
  declare module.exports: any;
}

declare module '@njmyers/component-library/src/SemiSticky/SemiSticky' {
  declare module.exports: any;
}

declare module '@njmyers/component-library/src/SemiSticky/stories/LongPage' {
  declare module.exports: any;
}

declare module '@njmyers/component-library/src/SemiSticky/stories/semi-sticky.stories' {
  declare module.exports: any;
}

declare module '@njmyers/component-library/src/SlideShow/index' {
  declare module.exports: any;
}

declare module '@njmyers/component-library/src/SlideShow/SlideShow' {
  declare module.exports: any;
}

declare module '@njmyers/component-library/src/SlideShow/stories/slide-show.stories' {
  declare module.exports: any;
}

declare module '@njmyers/component-library/src/StatusSwitch/__tests__/StatusSwitch.test' {
  declare module.exports: any;
}

declare module '@njmyers/component-library/src/StatusSwitch/index' {
  declare module.exports: any;
}

declare module '@njmyers/component-library/src/StatusSwitch/StatusSwitch' {
  declare module.exports: any;
}

declare module '@njmyers/component-library/src/StatusSwitch/stories/Demo' {
  declare module.exports: any;
}

declare module '@njmyers/component-library/src/StatusSwitch/stories/status-switch.stories' {
  declare module.exports: any;
}

declare module '@njmyers/component-library/src/Title/index' {
  declare module.exports: any;
}

declare module '@njmyers/component-library/src/Title/Title' {
  declare module.exports: any;
}

declare module '@njmyers/component-library/src/utils/__tests__/create-transition-style.test' {
  declare module.exports: any;
}

declare module '@njmyers/component-library/src/utils/create-transition-style' {
  declare module.exports: any;
}

// Filename aliases
declare module '@njmyers/component-library/babel.config.js' {
  declare module.exports: $Exports<'@njmyers/component-library/babel.config'>;
}
declare module '@njmyers/component-library/build/components.cjs.js' {
  declare module.exports: $Exports<'@njmyers/component-library/build/components.cjs'>;
}
declare module '@njmyers/component-library/build/components.esm.js' {
  declare module.exports: $Exports<'@njmyers/component-library/build/components.esm'>;
}
declare module '@njmyers/component-library/rollup.config.js' {
  declare module.exports: $Exports<'@njmyers/component-library/rollup.config'>;
}
declare module '@njmyers/component-library/scripts/docgen.js' {
  declare module.exports: $Exports<'@njmyers/component-library/scripts/docgen'>;
}
declare module '@njmyers/component-library/scripts/generate-markdown.js' {
  declare module.exports: $Exports<'@njmyers/component-library/scripts/generate-markdown'>;
}
declare module '@njmyers/component-library/scripts/readme.js' {
  declare module.exports: $Exports<'@njmyers/component-library/scripts/readme'>;
}
declare module '@njmyers/component-library/src/BEM/__tests__/BEM.integration.test.js' {
  declare module.exports: $Exports<'@njmyers/component-library/src/BEM/__tests__/BEM.integration.test'>;
}
declare module '@njmyers/component-library/src/BEM/__tests__/BEM.unit.test.js' {
  declare module.exports: $Exports<'@njmyers/component-library/src/BEM/__tests__/BEM.unit.test'>;
}
declare module '@njmyers/component-library/src/BEM/BEM.js' {
  declare module.exports: $Exports<'@njmyers/component-library/src/BEM/BEM'>;
}
declare module '@njmyers/component-library/src/BEM/index.js' {
  declare module.exports: $Exports<'@njmyers/component-library/src/BEM/index'>;
}
declare module '@njmyers/component-library/src/ErrorMessage/ErrorMessage.js' {
  declare module.exports: $Exports<'@njmyers/component-library/src/ErrorMessage/ErrorMessage'>;
}
declare module '@njmyers/component-library/src/ErrorMessage/index.js' {
  declare module.exports: $Exports<'@njmyers/component-library/src/ErrorMessage/index'>;
}
declare module '@njmyers/component-library/src/Form/__tests__/Input.test.js' {
  declare module.exports: $Exports<'@njmyers/component-library/src/Form/__tests__/Input.test'>;
}
declare module '@njmyers/component-library/src/Form/index.js' {
  declare module.exports: $Exports<'@njmyers/component-library/src/Form/index'>;
}
declare module '@njmyers/component-library/src/Form/Input.js' {
  declare module.exports: $Exports<'@njmyers/component-library/src/Form/Input'>;
}
declare module '@njmyers/component-library/src/Form/Select.js' {
  declare module.exports: $Exports<'@njmyers/component-library/src/Form/Select'>;
}
declare module '@njmyers/component-library/src/Form/Submit.js' {
  declare module.exports: $Exports<'@njmyers/component-library/src/Form/Submit'>;
}
declare module '@njmyers/component-library/src/Form/TextArea.js' {
  declare module.exports: $Exports<'@njmyers/component-library/src/Form/TextArea'>;
}
declare module '@njmyers/component-library/src/Icon/Arrow.js' {
  declare module.exports: $Exports<'@njmyers/component-library/src/Icon/Arrow'>;
}
declare module '@njmyers/component-library/src/Icon/Bag.js' {
  declare module.exports: $Exports<'@njmyers/component-library/src/Icon/Bag'>;
}
declare module '@njmyers/component-library/src/Icon/Caret.js' {
  declare module.exports: $Exports<'@njmyers/component-library/src/Icon/Caret'>;
}
declare module '@njmyers/component-library/src/Icon/Circle.js' {
  declare module.exports: $Exports<'@njmyers/component-library/src/Icon/Circle'>;
}
declare module '@njmyers/component-library/src/Icon/Cross.js' {
  declare module.exports: $Exports<'@njmyers/component-library/src/Icon/Cross'>;
}
declare module '@njmyers/component-library/src/Icon/Hamburger.js' {
  declare module.exports: $Exports<'@njmyers/component-library/src/Icon/Hamburger'>;
}
declare module '@njmyers/component-library/src/Icon/Icon.js' {
  declare module.exports: $Exports<'@njmyers/component-library/src/Icon/Icon'>;
}
declare module '@njmyers/component-library/src/Icon/index.js' {
  declare module.exports: $Exports<'@njmyers/component-library/src/Icon/index'>;
}
declare module '@njmyers/component-library/src/Icon/Minus.js' {
  declare module.exports: $Exports<'@njmyers/component-library/src/Icon/Minus'>;
}
declare module '@njmyers/component-library/src/Icon/Plus.js' {
  declare module.exports: $Exports<'@njmyers/component-library/src/Icon/Plus'>;
}
declare module '@njmyers/component-library/src/Icon/Ring.js' {
  declare module.exports: $Exports<'@njmyers/component-library/src/Icon/Ring'>;
}
declare module '@njmyers/component-library/src/Icon/RingSlash.js' {
  declare module.exports: $Exports<'@njmyers/component-library/src/Icon/RingSlash'>;
}
declare module '@njmyers/component-library/src/Icon/stories/icon.stories.js' {
  declare module.exports: $Exports<'@njmyers/component-library/src/Icon/stories/icon.stories'>;
}
declare module '@njmyers/component-library/src/index.js' {
  declare module.exports: $Exports<'@njmyers/component-library/src/index'>;
}
declare module '@njmyers/component-library/src/LazyImage/index.js' {
  declare module.exports: $Exports<'@njmyers/component-library/src/LazyImage/index'>;
}
declare module '@njmyers/component-library/src/LazyImage/LazyImage.js' {
  declare module.exports: $Exports<'@njmyers/component-library/src/LazyImage/LazyImage'>;
}
declare module '@njmyers/component-library/src/LazyImage/stories/Changer.js' {
  declare module.exports: $Exports<'@njmyers/component-library/src/LazyImage/stories/Changer'>;
}
declare module '@njmyers/component-library/src/LazyImage/stories/image.stories.js' {
  declare module.exports: $Exports<'@njmyers/component-library/src/LazyImage/stories/image.stories'>;
}
declare module '@njmyers/component-library/src/loadComponent/__tests__/loadComponent.test.js' {
  declare module.exports: $Exports<'@njmyers/component-library/src/loadComponent/__tests__/loadComponent.test'>;
}
declare module '@njmyers/component-library/src/loadComponent/index.js' {
  declare module.exports: $Exports<'@njmyers/component-library/src/loadComponent/index'>;
}
declare module '@njmyers/component-library/src/loadComponent/loadComponent.js' {
  declare module.exports: $Exports<'@njmyers/component-library/src/loadComponent/loadComponent'>;
}
declare module '@njmyers/component-library/src/loadComponent/TestComponent.js' {
  declare module.exports: $Exports<'@njmyers/component-library/src/loadComponent/TestComponent'>;
}
declare module '@njmyers/component-library/src/Loading/index.js' {
  declare module.exports: $Exports<'@njmyers/component-library/src/Loading/index'>;
}
declare module '@njmyers/component-library/src/Loading/Loading.js' {
  declare module.exports: $Exports<'@njmyers/component-library/src/Loading/Loading'>;
}
declare module '@njmyers/component-library/src/Loading/stories/loading.stories.js' {
  declare module.exports: $Exports<'@njmyers/component-library/src/Loading/stories/loading.stories'>;
}
declare module '@njmyers/component-library/src/Modal/index.js' {
  declare module.exports: $Exports<'@njmyers/component-library/src/Modal/index'>;
}
declare module '@njmyers/component-library/src/Modal/Modal.js' {
  declare module.exports: $Exports<'@njmyers/component-library/src/Modal/Modal'>;
}
declare module '@njmyers/component-library/src/Modal/ModalUnstyled.js' {
  declare module.exports: $Exports<'@njmyers/component-library/src/Modal/ModalUnstyled'>;
}
declare module '@njmyers/component-library/src/Modal/stories/modal.stories.js' {
  declare module.exports: $Exports<'@njmyers/component-library/src/Modal/stories/modal.stories'>;
}
declare module '@njmyers/component-library/src/Scratch/Headings.js' {
  declare module.exports: $Exports<'@njmyers/component-library/src/Scratch/Headings'>;
}
declare module '@njmyers/component-library/src/Scratch/LoremIpsum.js' {
  declare module.exports: $Exports<'@njmyers/component-library/src/Scratch/LoremIpsum'>;
}
declare module '@njmyers/component-library/src/SemiSticky/__tests__/SemiSticky.test.js' {
  declare module.exports: $Exports<'@njmyers/component-library/src/SemiSticky/__tests__/SemiSticky.test'>;
}
declare module '@njmyers/component-library/src/SemiSticky/index.js' {
  declare module.exports: $Exports<'@njmyers/component-library/src/SemiSticky/index'>;
}
declare module '@njmyers/component-library/src/SemiSticky/SemiSticky.js' {
  declare module.exports: $Exports<'@njmyers/component-library/src/SemiSticky/SemiSticky'>;
}
declare module '@njmyers/component-library/src/SemiSticky/stories/LongPage.js' {
  declare module.exports: $Exports<'@njmyers/component-library/src/SemiSticky/stories/LongPage'>;
}
declare module '@njmyers/component-library/src/SemiSticky/stories/semi-sticky.stories.js' {
  declare module.exports: $Exports<'@njmyers/component-library/src/SemiSticky/stories/semi-sticky.stories'>;
}
declare module '@njmyers/component-library/src/SlideShow/index.js' {
  declare module.exports: $Exports<'@njmyers/component-library/src/SlideShow/index'>;
}
declare module '@njmyers/component-library/src/SlideShow/SlideShow.js' {
  declare module.exports: $Exports<'@njmyers/component-library/src/SlideShow/SlideShow'>;
}
declare module '@njmyers/component-library/src/SlideShow/stories/slide-show.stories.js' {
  declare module.exports: $Exports<'@njmyers/component-library/src/SlideShow/stories/slide-show.stories'>;
}
declare module '@njmyers/component-library/src/StatusSwitch/__tests__/StatusSwitch.test.js' {
  declare module.exports: $Exports<'@njmyers/component-library/src/StatusSwitch/__tests__/StatusSwitch.test'>;
}
declare module '@njmyers/component-library/src/StatusSwitch/index.js' {
  declare module.exports: $Exports<'@njmyers/component-library/src/StatusSwitch/index'>;
}
declare module '@njmyers/component-library/src/StatusSwitch/StatusSwitch.js' {
  declare module.exports: $Exports<'@njmyers/component-library/src/StatusSwitch/StatusSwitch'>;
}
declare module '@njmyers/component-library/src/StatusSwitch/stories/Demo.js' {
  declare module.exports: $Exports<'@njmyers/component-library/src/StatusSwitch/stories/Demo'>;
}
declare module '@njmyers/component-library/src/StatusSwitch/stories/status-switch.stories.js' {
  declare module.exports: $Exports<'@njmyers/component-library/src/StatusSwitch/stories/status-switch.stories'>;
}
declare module '@njmyers/component-library/src/Title/index.js' {
  declare module.exports: $Exports<'@njmyers/component-library/src/Title/index'>;
}
declare module '@njmyers/component-library/src/Title/Title.js' {
  declare module.exports: $Exports<'@njmyers/component-library/src/Title/Title'>;
}
declare module '@njmyers/component-library/src/utils/__tests__/create-transition-style.test.js' {
  declare module.exports: $Exports<'@njmyers/component-library/src/utils/__tests__/create-transition-style.test'>;
}
declare module '@njmyers/component-library/src/utils/create-transition-style.js' {
  declare module.exports: $Exports<'@njmyers/component-library/src/utils/create-transition-style'>;
}
