// flow-typed signature: 3263c2aeb53ff333d817ab7e493af586
// flow-typed version: <<STUB>>/@artetexture/templates_v^0.0.1/flow_v0.83.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   '@artetexture/templates'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module '@artetexture/templates' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module '@artetexture/templates/babel.config' {
  declare module.exports: any;
}

declare module '@artetexture/templates/build/templates.cjs' {
  declare module.exports: any;
}

declare module '@artetexture/templates/build/templates.esm' {
  declare module.exports: any;
}

declare module '@artetexture/templates/flow-typed/npm/@artetexture/checkout-objects_vx.x.x' {
  declare module.exports: any;
}

declare module '@artetexture/templates/flow-typed/npm/@babel/runtime_vx.x.x' {
  declare module.exports: any;
}

declare module '@artetexture/templates/flow-typed/npm/smalldash_vx.x.x' {
  declare module.exports: any;
}

declare module '@artetexture/templates/rollup.config' {
  declare module.exports: any;
}

declare module '@artetexture/templates/src/Customer/Customer' {
  declare module.exports: any;
}

declare module '@artetexture/templates/src/Customer/index' {
  declare module.exports: any;
}

declare module '@artetexture/templates/src/index' {
  declare module.exports: any;
}

declare module '@artetexture/templates/src/Line/index' {
  declare module.exports: any;
}

declare module '@artetexture/templates/src/Line/Line' {
  declare module.exports: any;
}

declare module '@artetexture/templates/src/OrderConfirmation/index' {
  declare module.exports: any;
}

declare module '@artetexture/templates/src/OrderConfirmation/OrderConfirmation' {
  declare module.exports: any;
}

declare module '@artetexture/templates/src/ServerAddress/index' {
  declare module.exports: any;
}

declare module '@artetexture/templates/src/ServerAddress/ServerAddress' {
  declare module.exports: any;
}

// Filename aliases
declare module '@artetexture/templates/babel.config.js' {
  declare module.exports: $Exports<'@artetexture/templates/babel.config'>;
}
declare module '@artetexture/templates/build/templates.cjs.js' {
  declare module.exports: $Exports<'@artetexture/templates/build/templates.cjs'>;
}
declare module '@artetexture/templates/build/templates.esm.js' {
  declare module.exports: $Exports<'@artetexture/templates/build/templates.esm'>;
}
declare module '@artetexture/templates/flow-typed/npm/@artetexture/checkout-objects_vx.x.x.js' {
  declare module.exports: $Exports<'@artetexture/templates/flow-typed/npm/@artetexture/checkout-objects_vx.x.x'>;
}
declare module '@artetexture/templates/flow-typed/npm/@babel/runtime_vx.x.x.js' {
  declare module.exports: $Exports<'@artetexture/templates/flow-typed/npm/@babel/runtime_vx.x.x'>;
}
declare module '@artetexture/templates/flow-typed/npm/smalldash_vx.x.x.js' {
  declare module.exports: $Exports<'@artetexture/templates/flow-typed/npm/smalldash_vx.x.x'>;
}
declare module '@artetexture/templates/rollup.config.js' {
  declare module.exports: $Exports<'@artetexture/templates/rollup.config'>;
}
declare module '@artetexture/templates/src/Customer/Customer.js' {
  declare module.exports: $Exports<'@artetexture/templates/src/Customer/Customer'>;
}
declare module '@artetexture/templates/src/Customer/index.js' {
  declare module.exports: $Exports<'@artetexture/templates/src/Customer/index'>;
}
declare module '@artetexture/templates/src/index.js' {
  declare module.exports: $Exports<'@artetexture/templates/src/index'>;
}
declare module '@artetexture/templates/src/Line/index.js' {
  declare module.exports: $Exports<'@artetexture/templates/src/Line/index'>;
}
declare module '@artetexture/templates/src/Line/Line.js' {
  declare module.exports: $Exports<'@artetexture/templates/src/Line/Line'>;
}
declare module '@artetexture/templates/src/OrderConfirmation/index.js' {
  declare module.exports: $Exports<'@artetexture/templates/src/OrderConfirmation/index'>;
}
declare module '@artetexture/templates/src/OrderConfirmation/OrderConfirmation.js' {
  declare module.exports: $Exports<'@artetexture/templates/src/OrderConfirmation/OrderConfirmation'>;
}
declare module '@artetexture/templates/src/ServerAddress/index.js' {
  declare module.exports: $Exports<'@artetexture/templates/src/ServerAddress/index'>;
}
declare module '@artetexture/templates/src/ServerAddress/ServerAddress.js' {
  declare module.exports: $Exports<'@artetexture/templates/src/ServerAddress/ServerAddress'>;
}
