// flow-typed signature: 21d42302bd30094f78944e0c0d125e9e
// flow-typed version: <<STUB>>/@byalejandradesign/server-env_v0.0.1/flow_v0.83.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   '@byalejandradesign/server-env'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module '@byalejandradesign/server-env' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module '@byalejandradesign/server-env/babel.config' {
  declare module.exports: any;
}

declare module '@byalejandradesign/server-env/build/env.cjs' {
  declare module.exports: any;
}

declare module '@byalejandradesign/server-env/build/env.esm' {
  declare module.exports: any;
}

declare module '@byalejandradesign/server-env/flow-typed/npm/express_v4.16.x' {
  declare module.exports: any;
}

declare module '@byalejandradesign/server-env/rollup.config' {
  declare module.exports: any;
}

declare module '@byalejandradesign/server-env/src/env' {
  declare module.exports: any;
}

declare module '@byalejandradesign/server-env/src/normalize-domain' {
  declare module.exports: any;
}

declare module '@byalejandradesign/server-env/validate-env' {
  declare module.exports: any;
}

// Filename aliases
declare module '@byalejandradesign/server-env/babel.config.js' {
  declare module.exports: $Exports<'@byalejandradesign/server-env/babel.config'>;
}
declare module '@byalejandradesign/server-env/build/env.cjs.js' {
  declare module.exports: $Exports<'@byalejandradesign/server-env/build/env.cjs'>;
}
declare module '@byalejandradesign/server-env/build/env.esm.js' {
  declare module.exports: $Exports<'@byalejandradesign/server-env/build/env.esm'>;
}
declare module '@byalejandradesign/server-env/flow-typed/npm/express_v4.16.x.js' {
  declare module.exports: $Exports<'@byalejandradesign/server-env/flow-typed/npm/express_v4.16.x'>;
}
declare module '@byalejandradesign/server-env/rollup.config.js' {
  declare module.exports: $Exports<'@byalejandradesign/server-env/rollup.config'>;
}
declare module '@byalejandradesign/server-env/src/env.js' {
  declare module.exports: $Exports<'@byalejandradesign/server-env/src/env'>;
}
declare module '@byalejandradesign/server-env/src/normalize-domain.js' {
  declare module.exports: $Exports<'@byalejandradesign/server-env/src/normalize-domain'>;
}
declare module '@byalejandradesign/server-env/validate-env.js' {
  declare module.exports: $Exports<'@byalejandradesign/server-env/validate-env'>;
}
