// flow-typed signature: b9f18ac2911e1f33b9797e0fc3b6cf36
// flow-typed version: <<STUB>>/@artetexture/checkout-objects_v^0.0.1/flow_v0.83.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   '@artetexture/checkout-objects'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module '@artetexture/checkout-objects' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module '@artetexture/checkout-objects/babel.config' {
  declare module.exports: any;
}

declare module '@artetexture/checkout-objects/build/index.cjs' {
  declare module.exports: any;
}

declare module '@artetexture/checkout-objects/build/index.esm' {
  declare module.exports: any;
}

declare module '@artetexture/checkout-objects/flow-typed/npm/@babel/runtime_vx.x.x' {
  declare module.exports: any;
}

declare module '@artetexture/checkout-objects/flow-typed/npm/smalldash_vx.x.x' {
  declare module.exports: any;
}

declare module '@artetexture/checkout-objects/flow-typed/npm/uuid_v3.x.x' {
  declare module.exports: any;
}

declare module '@artetexture/checkout-objects/rollup.config' {
  declare module.exports: any;
}

declare module '@artetexture/checkout-objects/src/index' {
  declare module.exports: any;
}

declare module '@artetexture/checkout-objects/src/objects/__tests__/order-id.test' {
  declare module.exports: any;
}

declare module '@artetexture/checkout-objects/src/objects/address' {
  declare module.exports: any;
}

declare module '@artetexture/checkout-objects/src/objects/credit-card-nonce' {
  declare module.exports: any;
}

declare module '@artetexture/checkout-objects/src/objects/customer' {
  declare module.exports: any;
}

declare module '@artetexture/checkout-objects/src/objects/defaults' {
  declare module.exports: any;
}

declare module '@artetexture/checkout-objects/src/objects/index' {
  declare module.exports: any;
}

declare module '@artetexture/checkout-objects/src/objects/line-item' {
  declare module.exports: any;
}

declare module '@artetexture/checkout-objects/src/objects/order-id' {
  declare module.exports: any;
}

declare module '@artetexture/checkout-objects/src/objects/paypal-address' {
  declare module.exports: any;
}

declare module '@artetexture/checkout-objects/src/objects/paypal-nonce' {
  declare module.exports: any;
}

declare module '@artetexture/checkout-objects/src/objects/server-address' {
  declare module.exports: any;
}

declare module '@artetexture/checkout-objects/src/objects/transaction' {
  declare module.exports: any;
}

declare module '@artetexture/checkout-objects/src/objects/types' {
  declare module.exports: any;
}

declare module '@artetexture/checkout-objects/src/transformers/__tests__/address-transformers.test' {
  declare module.exports: any;
}

declare module '@artetexture/checkout-objects/src/transformers/address-to-paypal-address' {
  declare module.exports: any;
}

declare module '@artetexture/checkout-objects/src/transformers/address-to-server-address' {
  declare module.exports: any;
}

declare module '@artetexture/checkout-objects/src/transformers/index' {
  declare module.exports: any;
}

declare module '@artetexture/checkout-objects/src/transformers/types' {
  declare module.exports: any;
}

declare module '@artetexture/checkout-objects/src/validators/__tests__/address-validators.test' {
  declare module.exports: any;
}

declare module '@artetexture/checkout-objects/src/validators/check-required' {
  declare module.exports: any;
}

declare module '@artetexture/checkout-objects/src/validators/index' {
  declare module.exports: any;
}

declare module '@artetexture/checkout-objects/src/validators/types' {
  declare module.exports: any;
}

declare module '@artetexture/checkout-objects/src/validators/validate-address' {
  declare module.exports: any;
}

declare module '@artetexture/checkout-objects/src/validators/validate-customer' {
  declare module.exports: any;
}

declare module '@artetexture/checkout-objects/src/validators/validate-paypal-address' {
  declare module.exports: any;
}

declare module '@artetexture/checkout-objects/src/validators/validate-server-address' {
  declare module.exports: any;
}

declare module '@artetexture/checkout-objects/src/validators/validate-transaction' {
  declare module.exports: any;
}

// Filename aliases
declare module '@artetexture/checkout-objects/babel.config.js' {
  declare module.exports: $Exports<'@artetexture/checkout-objects/babel.config'>;
}
declare module '@artetexture/checkout-objects/build/index.cjs.js' {
  declare module.exports: $Exports<'@artetexture/checkout-objects/build/index.cjs'>;
}
declare module '@artetexture/checkout-objects/build/index.esm.js' {
  declare module.exports: $Exports<'@artetexture/checkout-objects/build/index.esm'>;
}
declare module '@artetexture/checkout-objects/flow-typed/npm/@babel/runtime_vx.x.x.js' {
  declare module.exports: $Exports<'@artetexture/checkout-objects/flow-typed/npm/@babel/runtime_vx.x.x'>;
}
declare module '@artetexture/checkout-objects/flow-typed/npm/smalldash_vx.x.x.js' {
  declare module.exports: $Exports<'@artetexture/checkout-objects/flow-typed/npm/smalldash_vx.x.x'>;
}
declare module '@artetexture/checkout-objects/flow-typed/npm/uuid_v3.x.x.js' {
  declare module.exports: $Exports<'@artetexture/checkout-objects/flow-typed/npm/uuid_v3.x.x'>;
}
declare module '@artetexture/checkout-objects/rollup.config.js' {
  declare module.exports: $Exports<'@artetexture/checkout-objects/rollup.config'>;
}
declare module '@artetexture/checkout-objects/src/index.js' {
  declare module.exports: $Exports<'@artetexture/checkout-objects/src/index'>;
}
declare module '@artetexture/checkout-objects/src/objects/__tests__/order-id.test.js' {
  declare module.exports: $Exports<'@artetexture/checkout-objects/src/objects/__tests__/order-id.test'>;
}
declare module '@artetexture/checkout-objects/src/objects/address.js' {
  declare module.exports: $Exports<'@artetexture/checkout-objects/src/objects/address'>;
}
declare module '@artetexture/checkout-objects/src/objects/credit-card-nonce.js' {
  declare module.exports: $Exports<'@artetexture/checkout-objects/src/objects/credit-card-nonce'>;
}
declare module '@artetexture/checkout-objects/src/objects/customer.js' {
  declare module.exports: $Exports<'@artetexture/checkout-objects/src/objects/customer'>;
}
declare module '@artetexture/checkout-objects/src/objects/defaults.js' {
  declare module.exports: $Exports<'@artetexture/checkout-objects/src/objects/defaults'>;
}
declare module '@artetexture/checkout-objects/src/objects/index.js' {
  declare module.exports: $Exports<'@artetexture/checkout-objects/src/objects/index'>;
}
declare module '@artetexture/checkout-objects/src/objects/line-item.js' {
  declare module.exports: $Exports<'@artetexture/checkout-objects/src/objects/line-item'>;
}
declare module '@artetexture/checkout-objects/src/objects/order-id.js' {
  declare module.exports: $Exports<'@artetexture/checkout-objects/src/objects/order-id'>;
}
declare module '@artetexture/checkout-objects/src/objects/paypal-address.js' {
  declare module.exports: $Exports<'@artetexture/checkout-objects/src/objects/paypal-address'>;
}
declare module '@artetexture/checkout-objects/src/objects/paypal-nonce.js' {
  declare module.exports: $Exports<'@artetexture/checkout-objects/src/objects/paypal-nonce'>;
}
declare module '@artetexture/checkout-objects/src/objects/server-address.js' {
  declare module.exports: $Exports<'@artetexture/checkout-objects/src/objects/server-address'>;
}
declare module '@artetexture/checkout-objects/src/objects/transaction.js' {
  declare module.exports: $Exports<'@artetexture/checkout-objects/src/objects/transaction'>;
}
declare module '@artetexture/checkout-objects/src/objects/types.js' {
  declare module.exports: $Exports<'@artetexture/checkout-objects/src/objects/types'>;
}
declare module '@artetexture/checkout-objects/src/transformers/__tests__/address-transformers.test.js' {
  declare module.exports: $Exports<'@artetexture/checkout-objects/src/transformers/__tests__/address-transformers.test'>;
}
declare module '@artetexture/checkout-objects/src/transformers/address-to-paypal-address.js' {
  declare module.exports: $Exports<'@artetexture/checkout-objects/src/transformers/address-to-paypal-address'>;
}
declare module '@artetexture/checkout-objects/src/transformers/address-to-server-address.js' {
  declare module.exports: $Exports<'@artetexture/checkout-objects/src/transformers/address-to-server-address'>;
}
declare module '@artetexture/checkout-objects/src/transformers/index.js' {
  declare module.exports: $Exports<'@artetexture/checkout-objects/src/transformers/index'>;
}
declare module '@artetexture/checkout-objects/src/transformers/types.js' {
  declare module.exports: $Exports<'@artetexture/checkout-objects/src/transformers/types'>;
}
declare module '@artetexture/checkout-objects/src/validators/__tests__/address-validators.test.js' {
  declare module.exports: $Exports<'@artetexture/checkout-objects/src/validators/__tests__/address-validators.test'>;
}
declare module '@artetexture/checkout-objects/src/validators/check-required.js' {
  declare module.exports: $Exports<'@artetexture/checkout-objects/src/validators/check-required'>;
}
declare module '@artetexture/checkout-objects/src/validators/index.js' {
  declare module.exports: $Exports<'@artetexture/checkout-objects/src/validators/index'>;
}
declare module '@artetexture/checkout-objects/src/validators/types.js' {
  declare module.exports: $Exports<'@artetexture/checkout-objects/src/validators/types'>;
}
declare module '@artetexture/checkout-objects/src/validators/validate-address.js' {
  declare module.exports: $Exports<'@artetexture/checkout-objects/src/validators/validate-address'>;
}
declare module '@artetexture/checkout-objects/src/validators/validate-customer.js' {
  declare module.exports: $Exports<'@artetexture/checkout-objects/src/validators/validate-customer'>;
}
declare module '@artetexture/checkout-objects/src/validators/validate-paypal-address.js' {
  declare module.exports: $Exports<'@artetexture/checkout-objects/src/validators/validate-paypal-address'>;
}
declare module '@artetexture/checkout-objects/src/validators/validate-server-address.js' {
  declare module.exports: $Exports<'@artetexture/checkout-objects/src/validators/validate-server-address'>;
}
declare module '@artetexture/checkout-objects/src/validators/validate-transaction.js' {
  declare module.exports: $Exports<'@artetexture/checkout-objects/src/validators/validate-transaction'>;
}
