// flow-typed signature: a77b1ba09b7111264a4924d932d66499
// flow-typed version: <<STUB>>/@artetexture/data-objects_v^0.0.1/flow_v0.83.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   '@artetexture/data-objects'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module '@artetexture/data-objects' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module '@artetexture/data-objects/babel.config' {
  declare module.exports: any;
}

declare module '@artetexture/data-objects/build/index.cjs' {
  declare module.exports: any;
}

declare module '@artetexture/data-objects/build/index.esm' {
  declare module.exports: any;
}

declare module '@artetexture/data-objects/flow-typed/npm/@babel/runtime_vx.x.x' {
  declare module.exports: any;
}

declare module '@artetexture/data-objects/flow-typed/npm/gatsby_vx.x.x' {
  declare module.exports: any;
}

declare module '@artetexture/data-objects/flow-typed/npm/graphql-type-json_vx.x.x' {
  declare module.exports: any;
}

declare module '@artetexture/data-objects/queries/graphql' {
  declare module.exports: any;
}

declare module '@artetexture/data-objects/queries/index' {
  declare module.exports: any;
}

declare module '@artetexture/data-objects/queries/posts' {
  declare module.exports: any;
}

declare module '@artetexture/data-objects/rollup.config' {
  declare module.exports: any;
}

declare module '@artetexture/data-objects/src/index' {
  declare module.exports: any;
}

declare module '@artetexture/data-objects/src/queries/index' {
  declare module.exports: any;
}

declare module '@artetexture/data-objects/src/queries/posts' {
  declare module.exports: any;
}

declare module '@artetexture/data-objects/src/types' {
  declare module.exports: any;
}

// Filename aliases
declare module '@artetexture/data-objects/babel.config.js' {
  declare module.exports: $Exports<'@artetexture/data-objects/babel.config'>;
}
declare module '@artetexture/data-objects/build/index.cjs.js' {
  declare module.exports: $Exports<'@artetexture/data-objects/build/index.cjs'>;
}
declare module '@artetexture/data-objects/build/index.esm.js' {
  declare module.exports: $Exports<'@artetexture/data-objects/build/index.esm'>;
}
declare module '@artetexture/data-objects/flow-typed/npm/@babel/runtime_vx.x.x.js' {
  declare module.exports: $Exports<'@artetexture/data-objects/flow-typed/npm/@babel/runtime_vx.x.x'>;
}
declare module '@artetexture/data-objects/flow-typed/npm/gatsby_vx.x.x.js' {
  declare module.exports: $Exports<'@artetexture/data-objects/flow-typed/npm/gatsby_vx.x.x'>;
}
declare module '@artetexture/data-objects/flow-typed/npm/graphql-type-json_vx.x.x.js' {
  declare module.exports: $Exports<'@artetexture/data-objects/flow-typed/npm/graphql-type-json_vx.x.x'>;
}
declare module '@artetexture/data-objects/queries/graphql.js' {
  declare module.exports: $Exports<'@artetexture/data-objects/queries/graphql'>;
}
declare module '@artetexture/data-objects/queries/index.js' {
  declare module.exports: $Exports<'@artetexture/data-objects/queries/index'>;
}
declare module '@artetexture/data-objects/queries/posts.js' {
  declare module.exports: $Exports<'@artetexture/data-objects/queries/posts'>;
}
declare module '@artetexture/data-objects/rollup.config.js' {
  declare module.exports: $Exports<'@artetexture/data-objects/rollup.config'>;
}
declare module '@artetexture/data-objects/src/index.js' {
  declare module.exports: $Exports<'@artetexture/data-objects/src/index'>;
}
declare module '@artetexture/data-objects/src/queries/index.js' {
  declare module.exports: $Exports<'@artetexture/data-objects/src/queries/index'>;
}
declare module '@artetexture/data-objects/src/queries/posts.js' {
  declare module.exports: $Exports<'@artetexture/data-objects/src/queries/posts'>;
}
declare module '@artetexture/data-objects/src/types.js' {
  declare module.exports: $Exports<'@artetexture/data-objects/src/types'>;
}
