// flow-typed signature: 9a2b893e9c42fdd3fa61f74f313f2be6
// flow-typed version: <<STUB>>/braintree-web_v^3.34.0/flow_v0.83.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'braintree-web'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'braintree-web' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'braintree-web/american-express/american-express' {
  declare module.exports: any;
}

declare module 'braintree-web/american-express/errors' {
  declare module.exports: any;
}

declare module 'braintree-web/american-express/index' {
  declare module.exports: any;
}

declare module 'braintree-web/apple-pay/apple-pay' {
  declare module.exports: any;
}

declare module 'braintree-web/apple-pay/errors' {
  declare module.exports: any;
}

declare module 'braintree-web/apple-pay/index' {
  declare module.exports: any;
}

declare module 'braintree-web/client/browser-detection' {
  declare module.exports: any;
}

declare module 'braintree-web/client/client' {
  declare module.exports: any;
}

declare module 'braintree-web/client/constants' {
  declare module.exports: any;
}

declare module 'braintree-web/client/errors' {
  declare module.exports: any;
}

declare module 'braintree-web/client/get-configuration' {
  declare module.exports: any;
}

declare module 'braintree-web/client/index' {
  declare module.exports: any;
}

declare module 'braintree-web/client/request/ajax-driver' {
  declare module.exports: any;
}

declare module 'braintree-web/client/request/default-request' {
  declare module.exports: any;
}

declare module 'braintree-web/client/request/get-user-agent' {
  declare module.exports: any;
}

declare module 'braintree-web/client/request/graphql/adapters/configuration' {
  declare module.exports: any;
}

declare module 'braintree-web/client/request/graphql/adapters/credit-card-tokenization' {
  declare module.exports: any;
}

declare module 'braintree-web/client/request/graphql/adapters/error' {
  declare module.exports: any;
}

declare module 'braintree-web/client/request/graphql/generators/configuration' {
  declare module.exports: any;
}

declare module 'braintree-web/client/request/graphql/generators/credit-card-tokenization' {
  declare module.exports: any;
}

declare module 'braintree-web/client/request/graphql/index' {
  declare module.exports: any;
}

declare module 'braintree-web/client/request/graphql/request' {
  declare module.exports: any;
}

declare module 'braintree-web/client/request/index' {
  declare module.exports: any;
}

declare module 'braintree-web/client/request/is-http' {
  declare module.exports: any;
}

declare module 'braintree-web/client/request/jsonp-driver' {
  declare module.exports: any;
}

declare module 'braintree-web/client/request/parse-body' {
  declare module.exports: any;
}

declare module 'braintree-web/client/request/prep-body' {
  declare module.exports: any;
}

declare module 'braintree-web/client/request/xhr' {
  declare module.exports: any;
}

declare module 'braintree-web/data-collector/constants' {
  declare module.exports: any;
}

declare module 'braintree-web/data-collector/errors' {
  declare module.exports: any;
}

declare module 'braintree-web/data-collector/fraudnet' {
  declare module.exports: any;
}

declare module 'braintree-web/data-collector/index' {
  declare module.exports: any;
}

declare module 'braintree-web/data-collector/kount' {
  declare module.exports: any;
}

declare module 'braintree-web/data-collector/vendor/sjcl' {
  declare module.exports: any;
}

declare module 'braintree-web/dist/browser/american-express' {
  declare module.exports: any;
}

declare module 'braintree-web/dist/browser/apple-pay' {
  declare module.exports: any;
}

declare module 'braintree-web/dist/browser/client' {
  declare module.exports: any;
}

declare module 'braintree-web/dist/browser/data-collector' {
  declare module.exports: any;
}

declare module 'braintree-web/dist/browser/google-payment' {
  declare module.exports: any;
}

declare module 'braintree-web/dist/browser/hosted-fields' {
  declare module.exports: any;
}

declare module 'braintree-web/dist/browser/ideal' {
  declare module.exports: any;
}

declare module 'braintree-web/dist/browser/index' {
  declare module.exports: any;
}

declare module 'braintree-web/dist/browser/masterpass' {
  declare module.exports: any;
}

declare module 'braintree-web/dist/browser/payment-request' {
  declare module.exports: any;
}

declare module 'braintree-web/dist/browser/paypal-checkout' {
  declare module.exports: any;
}

declare module 'braintree-web/dist/browser/paypal' {
  declare module.exports: any;
}

declare module 'braintree-web/dist/browser/three-d-secure' {
  declare module.exports: any;
}

declare module 'braintree-web/dist/browser/unionpay' {
  declare module.exports: any;
}

declare module 'braintree-web/dist/browser/us-bank-account' {
  declare module.exports: any;
}

declare module 'braintree-web/dist/browser/vault-manager' {
  declare module.exports: any;
}

declare module 'braintree-web/dist/browser/venmo' {
  declare module.exports: any;
}

declare module 'braintree-web/dist/browser/visa-checkout' {
  declare module.exports: any;
}

declare module 'braintree-web/google-payment/browser-detection' {
  declare module.exports: any;
}

declare module 'braintree-web/google-payment/errors' {
  declare module.exports: any;
}

declare module 'braintree-web/google-payment/google-payment' {
  declare module.exports: any;
}

declare module 'braintree-web/google-payment/index' {
  declare module.exports: any;
}

declare module 'braintree-web/hosted-fields/external/attribute-validation-error' {
  declare module.exports: any;
}

declare module 'braintree-web/hosted-fields/external/compose-url' {
  declare module.exports: any;
}

declare module 'braintree-web/hosted-fields/external/get-styles-from-class' {
  declare module.exports: any;
}

declare module 'braintree-web/hosted-fields/external/hosted-fields' {
  declare module.exports: any;
}

declare module 'braintree-web/hosted-fields/external/inject-frame' {
  declare module.exports: any;
}

declare module 'braintree-web/hosted-fields/index' {
  declare module.exports: any;
}

declare module 'braintree-web/hosted-fields/shared/browser-detection' {
  declare module.exports: any;
}

declare module 'braintree-web/hosted-fields/shared/constants' {
  declare module.exports: any;
}

declare module 'braintree-web/hosted-fields/shared/errors' {
  declare module.exports: any;
}

declare module 'braintree-web/hosted-fields/shared/find-parent-tags' {
  declare module.exports: any;
}

declare module 'braintree-web/hosted-fields/shared/get-card-types' {
  declare module.exports: any;
}

declare module 'braintree-web/ideal/external/constants' {
  declare module.exports: any;
}

declare module 'braintree-web/ideal/external/ideal' {
  declare module.exports: any;
}

declare module 'braintree-web/ideal/index' {
  declare module.exports: any;
}

declare module 'braintree-web/ideal/shared/browser-detection' {
  declare module.exports: any;
}

declare module 'braintree-web/ideal/shared/errors' {
  declare module.exports: any;
}

declare module 'braintree-web/ideal/shared/events' {
  declare module.exports: any;
}

declare module 'braintree-web/ideal/static/sandbox-approval' {
  declare module.exports: any;
}

declare module 'braintree-web/lib/add-metadata' {
  declare module.exports: any;
}

declare module 'braintree-web/lib/analytics' {
  declare module.exports: any;
}

declare module 'braintree-web/lib/assets' {
  declare module.exports: any;
}

declare module 'braintree-web/lib/assign' {
  declare module.exports: any;
}

declare module 'braintree-web/lib/basic-component-verification' {
  declare module.exports: any;
}

declare module 'braintree-web/lib/batch-execute-functions' {
  declare module.exports: any;
}

declare module 'braintree-web/lib/braintree-error' {
  declare module.exports: any;
}

declare module 'braintree-web/lib/bus/check-origin' {
  declare module.exports: any;
}

declare module 'braintree-web/lib/bus/events' {
  declare module.exports: any;
}

declare module 'braintree-web/lib/bus/index' {
  declare module.exports: any;
}

declare module 'braintree-web/lib/camel-case-to-snake-case' {
  declare module.exports: any;
}

declare module 'braintree-web/lib/classlist' {
  declare module.exports: any;
}

declare module 'braintree-web/lib/constants' {
  declare module.exports: any;
}

declare module 'braintree-web/lib/convert-methods-to-error' {
  declare module.exports: any;
}

declare module 'braintree-web/lib/convert-to-braintree-error' {
  declare module.exports: any;
}

declare module 'braintree-web/lib/create-authorization-data' {
  declare module.exports: any;
}

declare module 'braintree-web/lib/create-restricted-input' {
  declare module.exports: any;
}

declare module 'braintree-web/lib/deferred' {
  declare module.exports: any;
}

declare module 'braintree-web/lib/destructor' {
  declare module.exports: any;
}

declare module 'braintree-web/lib/enumerate' {
  declare module.exports: any;
}

declare module 'braintree-web/lib/errors' {
  declare module.exports: any;
}

declare module 'braintree-web/lib/event-emitter' {
  declare module.exports: any;
}

declare module 'braintree-web/lib/fake-restricted-input' {
  declare module.exports: any;
}

declare module 'braintree-web/lib/frame-service/external/frame-service' {
  declare module.exports: any;
}

declare module 'braintree-web/lib/frame-service/external/index' {
  declare module.exports: any;
}

declare module 'braintree-web/lib/frame-service/external/strategies/modal' {
  declare module.exports: any;
}

declare module 'braintree-web/lib/frame-service/external/strategies/popup-bridge' {
  declare module.exports: any;
}

declare module 'braintree-web/lib/frame-service/external/strategies/popup/compose-options' {
  declare module.exports: any;
}

declare module 'braintree-web/lib/frame-service/external/strategies/popup/index' {
  declare module.exports: any;
}

declare module 'braintree-web/lib/frame-service/external/strategies/popup/position' {
  declare module.exports: any;
}

declare module 'braintree-web/lib/frame-service/shared/browser-detection' {
  declare module.exports: any;
}

declare module 'braintree-web/lib/frame-service/shared/constants' {
  declare module.exports: any;
}

declare module 'braintree-web/lib/frame-service/shared/errors' {
  declare module.exports: any;
}

declare module 'braintree-web/lib/frame-service/shared/events' {
  declare module.exports: any;
}

declare module 'braintree-web/lib/generate-google-pay-configuration' {
  declare module.exports: any;
}

declare module 'braintree-web/lib/is-date-string-before-or-on' {
  declare module.exports: any;
}

declare module 'braintree-web/lib/is-https' {
  declare module.exports: any;
}

declare module 'braintree-web/lib/is-verified-domain' {
  declare module.exports: any;
}

declare module 'braintree-web/lib/json-clone' {
  declare module.exports: any;
}

declare module 'braintree-web/lib/methods' {
  declare module.exports: any;
}

declare module 'braintree-web/lib/once' {
  declare module.exports: any;
}

declare module 'braintree-web/lib/promise' {
  declare module.exports: any;
}

declare module 'braintree-web/lib/querystring' {
  declare module.exports: any;
}

declare module 'braintree-web/lib/redirect' {
  declare module.exports: any;
}

declare module 'braintree-web/lib/sanitize-html' {
  declare module.exports: any;
}

declare module 'braintree-web/lib/supports-passive-event-listener' {
  declare module.exports: any;
}

declare module 'braintree-web/lib/use-min' {
  declare module.exports: any;
}

declare module 'braintree-web/lib/vendor/polyfill' {
  declare module.exports: any;
}

declare module 'braintree-web/lib/vendor/uuid' {
  declare module.exports: any;
}

declare module 'braintree-web/masterpass/external/masterpass' {
  declare module.exports: any;
}

declare module 'braintree-web/masterpass/index' {
  declare module.exports: any;
}

declare module 'braintree-web/masterpass/shared/browser-detection' {
  declare module.exports: any;
}

declare module 'braintree-web/masterpass/shared/constants' {
  declare module.exports: any;
}

declare module 'braintree-web/masterpass/shared/errors' {
  declare module.exports: any;
}

declare module 'braintree-web/payment-request/external/payment-request' {
  declare module.exports: any;
}

declare module 'braintree-web/payment-request/index' {
  declare module.exports: any;
}

declare module 'braintree-web/payment-request/shared/constants' {
  declare module.exports: any;
}

declare module 'braintree-web/payment-request/shared/errors' {
  declare module.exports: any;
}

declare module 'braintree-web/paypal-checkout/errors' {
  declare module.exports: any;
}

declare module 'braintree-web/paypal-checkout/index' {
  declare module.exports: any;
}

declare module 'braintree-web/paypal-checkout/paypal-checkout' {
  declare module.exports: any;
}

declare module 'braintree-web/paypal/external/paypal' {
  declare module.exports: any;
}

declare module 'braintree-web/paypal/index' {
  declare module.exports: any;
}

declare module 'braintree-web/paypal/shared/constants' {
  declare module.exports: any;
}

declare module 'braintree-web/paypal/shared/errors' {
  declare module.exports: any;
}

declare module 'braintree-web/three-d-secure/external/three-d-secure' {
  declare module.exports: any;
}

declare module 'braintree-web/three-d-secure/index' {
  declare module.exports: any;
}

declare module 'braintree-web/three-d-secure/shared/constants' {
  declare module.exports: any;
}

declare module 'braintree-web/three-d-secure/shared/errors' {
  declare module.exports: any;
}

declare module 'braintree-web/three-d-secure/shared/events' {
  declare module.exports: any;
}

declare module 'braintree-web/unionpay/index' {
  declare module.exports: any;
}

declare module 'braintree-web/unionpay/shared/constants' {
  declare module.exports: any;
}

declare module 'braintree-web/unionpay/shared/errors' {
  declare module.exports: any;
}

declare module 'braintree-web/unionpay/shared/unionpay' {
  declare module.exports: any;
}

declare module 'braintree-web/us-bank-account/constants' {
  declare module.exports: any;
}

declare module 'braintree-web/us-bank-account/errors' {
  declare module.exports: any;
}

declare module 'braintree-web/us-bank-account/index' {
  declare module.exports: any;
}

declare module 'braintree-web/us-bank-account/us-bank-account' {
  declare module.exports: any;
}

declare module 'braintree-web/vault-manager/errors' {
  declare module.exports: any;
}

declare module 'braintree-web/vault-manager/index' {
  declare module.exports: any;
}

declare module 'braintree-web/vault-manager/vault-manager' {
  declare module.exports: any;
}

declare module 'braintree-web/venmo/index' {
  declare module.exports: any;
}

declare module 'braintree-web/venmo/shared/browser-detection' {
  declare module.exports: any;
}

declare module 'braintree-web/venmo/shared/constants' {
  declare module.exports: any;
}

declare module 'braintree-web/venmo/shared/errors' {
  declare module.exports: any;
}

declare module 'braintree-web/venmo/shared/supports-venmo' {
  declare module.exports: any;
}

declare module 'braintree-web/venmo/venmo' {
  declare module.exports: any;
}

declare module 'braintree-web/visa-checkout/errors' {
  declare module.exports: any;
}

declare module 'braintree-web/visa-checkout/index' {
  declare module.exports: any;
}

declare module 'braintree-web/visa-checkout/visa-checkout' {
  declare module.exports: any;
}

// Filename aliases
declare module 'braintree-web/american-express/american-express.js' {
  declare module.exports: $Exports<'braintree-web/american-express/american-express'>;
}
declare module 'braintree-web/american-express/errors.js' {
  declare module.exports: $Exports<'braintree-web/american-express/errors'>;
}
declare module 'braintree-web/american-express/index.js' {
  declare module.exports: $Exports<'braintree-web/american-express/index'>;
}
declare module 'braintree-web/apple-pay/apple-pay.js' {
  declare module.exports: $Exports<'braintree-web/apple-pay/apple-pay'>;
}
declare module 'braintree-web/apple-pay/errors.js' {
  declare module.exports: $Exports<'braintree-web/apple-pay/errors'>;
}
declare module 'braintree-web/apple-pay/index.js' {
  declare module.exports: $Exports<'braintree-web/apple-pay/index'>;
}
declare module 'braintree-web/client/browser-detection.js' {
  declare module.exports: $Exports<'braintree-web/client/browser-detection'>;
}
declare module 'braintree-web/client/client.js' {
  declare module.exports: $Exports<'braintree-web/client/client'>;
}
declare module 'braintree-web/client/constants.js' {
  declare module.exports: $Exports<'braintree-web/client/constants'>;
}
declare module 'braintree-web/client/errors.js' {
  declare module.exports: $Exports<'braintree-web/client/errors'>;
}
declare module 'braintree-web/client/get-configuration.js' {
  declare module.exports: $Exports<'braintree-web/client/get-configuration'>;
}
declare module 'braintree-web/client/index.js' {
  declare module.exports: $Exports<'braintree-web/client/index'>;
}
declare module 'braintree-web/client/request/ajax-driver.js' {
  declare module.exports: $Exports<'braintree-web/client/request/ajax-driver'>;
}
declare module 'braintree-web/client/request/default-request.js' {
  declare module.exports: $Exports<'braintree-web/client/request/default-request'>;
}
declare module 'braintree-web/client/request/get-user-agent.js' {
  declare module.exports: $Exports<'braintree-web/client/request/get-user-agent'>;
}
declare module 'braintree-web/client/request/graphql/adapters/configuration.js' {
  declare module.exports: $Exports<'braintree-web/client/request/graphql/adapters/configuration'>;
}
declare module 'braintree-web/client/request/graphql/adapters/credit-card-tokenization.js' {
  declare module.exports: $Exports<'braintree-web/client/request/graphql/adapters/credit-card-tokenization'>;
}
declare module 'braintree-web/client/request/graphql/adapters/error.js' {
  declare module.exports: $Exports<'braintree-web/client/request/graphql/adapters/error'>;
}
declare module 'braintree-web/client/request/graphql/generators/configuration.js' {
  declare module.exports: $Exports<'braintree-web/client/request/graphql/generators/configuration'>;
}
declare module 'braintree-web/client/request/graphql/generators/credit-card-tokenization.js' {
  declare module.exports: $Exports<'braintree-web/client/request/graphql/generators/credit-card-tokenization'>;
}
declare module 'braintree-web/client/request/graphql/index.js' {
  declare module.exports: $Exports<'braintree-web/client/request/graphql/index'>;
}
declare module 'braintree-web/client/request/graphql/request.js' {
  declare module.exports: $Exports<'braintree-web/client/request/graphql/request'>;
}
declare module 'braintree-web/client/request/index.js' {
  declare module.exports: $Exports<'braintree-web/client/request/index'>;
}
declare module 'braintree-web/client/request/is-http.js' {
  declare module.exports: $Exports<'braintree-web/client/request/is-http'>;
}
declare module 'braintree-web/client/request/jsonp-driver.js' {
  declare module.exports: $Exports<'braintree-web/client/request/jsonp-driver'>;
}
declare module 'braintree-web/client/request/parse-body.js' {
  declare module.exports: $Exports<'braintree-web/client/request/parse-body'>;
}
declare module 'braintree-web/client/request/prep-body.js' {
  declare module.exports: $Exports<'braintree-web/client/request/prep-body'>;
}
declare module 'braintree-web/client/request/xhr.js' {
  declare module.exports: $Exports<'braintree-web/client/request/xhr'>;
}
declare module 'braintree-web/data-collector/constants.js' {
  declare module.exports: $Exports<'braintree-web/data-collector/constants'>;
}
declare module 'braintree-web/data-collector/errors.js' {
  declare module.exports: $Exports<'braintree-web/data-collector/errors'>;
}
declare module 'braintree-web/data-collector/fraudnet.js' {
  declare module.exports: $Exports<'braintree-web/data-collector/fraudnet'>;
}
declare module 'braintree-web/data-collector/index.js' {
  declare module.exports: $Exports<'braintree-web/data-collector/index'>;
}
declare module 'braintree-web/data-collector/kount.js' {
  declare module.exports: $Exports<'braintree-web/data-collector/kount'>;
}
declare module 'braintree-web/data-collector/vendor/sjcl.js' {
  declare module.exports: $Exports<'braintree-web/data-collector/vendor/sjcl'>;
}
declare module 'braintree-web/dist/browser/american-express.js' {
  declare module.exports: $Exports<'braintree-web/dist/browser/american-express'>;
}
declare module 'braintree-web/dist/browser/apple-pay.js' {
  declare module.exports: $Exports<'braintree-web/dist/browser/apple-pay'>;
}
declare module 'braintree-web/dist/browser/client.js' {
  declare module.exports: $Exports<'braintree-web/dist/browser/client'>;
}
declare module 'braintree-web/dist/browser/data-collector.js' {
  declare module.exports: $Exports<'braintree-web/dist/browser/data-collector'>;
}
declare module 'braintree-web/dist/browser/google-payment.js' {
  declare module.exports: $Exports<'braintree-web/dist/browser/google-payment'>;
}
declare module 'braintree-web/dist/browser/hosted-fields.js' {
  declare module.exports: $Exports<'braintree-web/dist/browser/hosted-fields'>;
}
declare module 'braintree-web/dist/browser/ideal.js' {
  declare module.exports: $Exports<'braintree-web/dist/browser/ideal'>;
}
declare module 'braintree-web/dist/browser/index.js' {
  declare module.exports: $Exports<'braintree-web/dist/browser/index'>;
}
declare module 'braintree-web/dist/browser/masterpass.js' {
  declare module.exports: $Exports<'braintree-web/dist/browser/masterpass'>;
}
declare module 'braintree-web/dist/browser/payment-request.js' {
  declare module.exports: $Exports<'braintree-web/dist/browser/payment-request'>;
}
declare module 'braintree-web/dist/browser/paypal-checkout.js' {
  declare module.exports: $Exports<'braintree-web/dist/browser/paypal-checkout'>;
}
declare module 'braintree-web/dist/browser/paypal.js' {
  declare module.exports: $Exports<'braintree-web/dist/browser/paypal'>;
}
declare module 'braintree-web/dist/browser/three-d-secure.js' {
  declare module.exports: $Exports<'braintree-web/dist/browser/three-d-secure'>;
}
declare module 'braintree-web/dist/browser/unionpay.js' {
  declare module.exports: $Exports<'braintree-web/dist/browser/unionpay'>;
}
declare module 'braintree-web/dist/browser/us-bank-account.js' {
  declare module.exports: $Exports<'braintree-web/dist/browser/us-bank-account'>;
}
declare module 'braintree-web/dist/browser/vault-manager.js' {
  declare module.exports: $Exports<'braintree-web/dist/browser/vault-manager'>;
}
declare module 'braintree-web/dist/browser/venmo.js' {
  declare module.exports: $Exports<'braintree-web/dist/browser/venmo'>;
}
declare module 'braintree-web/dist/browser/visa-checkout.js' {
  declare module.exports: $Exports<'braintree-web/dist/browser/visa-checkout'>;
}
declare module 'braintree-web/google-payment/browser-detection.js' {
  declare module.exports: $Exports<'braintree-web/google-payment/browser-detection'>;
}
declare module 'braintree-web/google-payment/errors.js' {
  declare module.exports: $Exports<'braintree-web/google-payment/errors'>;
}
declare module 'braintree-web/google-payment/google-payment.js' {
  declare module.exports: $Exports<'braintree-web/google-payment/google-payment'>;
}
declare module 'braintree-web/google-payment/index.js' {
  declare module.exports: $Exports<'braintree-web/google-payment/index'>;
}
declare module 'braintree-web/hosted-fields/external/attribute-validation-error.js' {
  declare module.exports: $Exports<'braintree-web/hosted-fields/external/attribute-validation-error'>;
}
declare module 'braintree-web/hosted-fields/external/compose-url.js' {
  declare module.exports: $Exports<'braintree-web/hosted-fields/external/compose-url'>;
}
declare module 'braintree-web/hosted-fields/external/get-styles-from-class.js' {
  declare module.exports: $Exports<'braintree-web/hosted-fields/external/get-styles-from-class'>;
}
declare module 'braintree-web/hosted-fields/external/hosted-fields.js' {
  declare module.exports: $Exports<'braintree-web/hosted-fields/external/hosted-fields'>;
}
declare module 'braintree-web/hosted-fields/external/inject-frame.js' {
  declare module.exports: $Exports<'braintree-web/hosted-fields/external/inject-frame'>;
}
declare module 'braintree-web/hosted-fields/index.js' {
  declare module.exports: $Exports<'braintree-web/hosted-fields/index'>;
}
declare module 'braintree-web/hosted-fields/shared/browser-detection.js' {
  declare module.exports: $Exports<'braintree-web/hosted-fields/shared/browser-detection'>;
}
declare module 'braintree-web/hosted-fields/shared/constants.js' {
  declare module.exports: $Exports<'braintree-web/hosted-fields/shared/constants'>;
}
declare module 'braintree-web/hosted-fields/shared/errors.js' {
  declare module.exports: $Exports<'braintree-web/hosted-fields/shared/errors'>;
}
declare module 'braintree-web/hosted-fields/shared/find-parent-tags.js' {
  declare module.exports: $Exports<'braintree-web/hosted-fields/shared/find-parent-tags'>;
}
declare module 'braintree-web/hosted-fields/shared/get-card-types.js' {
  declare module.exports: $Exports<'braintree-web/hosted-fields/shared/get-card-types'>;
}
declare module 'braintree-web/ideal/external/constants.js' {
  declare module.exports: $Exports<'braintree-web/ideal/external/constants'>;
}
declare module 'braintree-web/ideal/external/ideal.js' {
  declare module.exports: $Exports<'braintree-web/ideal/external/ideal'>;
}
declare module 'braintree-web/ideal/index.js' {
  declare module.exports: $Exports<'braintree-web/ideal/index'>;
}
declare module 'braintree-web/ideal/shared/browser-detection.js' {
  declare module.exports: $Exports<'braintree-web/ideal/shared/browser-detection'>;
}
declare module 'braintree-web/ideal/shared/errors.js' {
  declare module.exports: $Exports<'braintree-web/ideal/shared/errors'>;
}
declare module 'braintree-web/ideal/shared/events.js' {
  declare module.exports: $Exports<'braintree-web/ideal/shared/events'>;
}
declare module 'braintree-web/ideal/static/sandbox-approval.js' {
  declare module.exports: $Exports<'braintree-web/ideal/static/sandbox-approval'>;
}
declare module 'braintree-web/index' {
  declare module.exports: $Exports<'braintree-web'>;
}
declare module 'braintree-web/index.js' {
  declare module.exports: $Exports<'braintree-web'>;
}
declare module 'braintree-web/lib/add-metadata.js' {
  declare module.exports: $Exports<'braintree-web/lib/add-metadata'>;
}
declare module 'braintree-web/lib/analytics.js' {
  declare module.exports: $Exports<'braintree-web/lib/analytics'>;
}
declare module 'braintree-web/lib/assets.js' {
  declare module.exports: $Exports<'braintree-web/lib/assets'>;
}
declare module 'braintree-web/lib/assign.js' {
  declare module.exports: $Exports<'braintree-web/lib/assign'>;
}
declare module 'braintree-web/lib/basic-component-verification.js' {
  declare module.exports: $Exports<'braintree-web/lib/basic-component-verification'>;
}
declare module 'braintree-web/lib/batch-execute-functions.js' {
  declare module.exports: $Exports<'braintree-web/lib/batch-execute-functions'>;
}
declare module 'braintree-web/lib/braintree-error.js' {
  declare module.exports: $Exports<'braintree-web/lib/braintree-error'>;
}
declare module 'braintree-web/lib/bus/check-origin.js' {
  declare module.exports: $Exports<'braintree-web/lib/bus/check-origin'>;
}
declare module 'braintree-web/lib/bus/events.js' {
  declare module.exports: $Exports<'braintree-web/lib/bus/events'>;
}
declare module 'braintree-web/lib/bus/index.js' {
  declare module.exports: $Exports<'braintree-web/lib/bus/index'>;
}
declare module 'braintree-web/lib/camel-case-to-snake-case.js' {
  declare module.exports: $Exports<'braintree-web/lib/camel-case-to-snake-case'>;
}
declare module 'braintree-web/lib/classlist.js' {
  declare module.exports: $Exports<'braintree-web/lib/classlist'>;
}
declare module 'braintree-web/lib/constants.js' {
  declare module.exports: $Exports<'braintree-web/lib/constants'>;
}
declare module 'braintree-web/lib/convert-methods-to-error.js' {
  declare module.exports: $Exports<'braintree-web/lib/convert-methods-to-error'>;
}
declare module 'braintree-web/lib/convert-to-braintree-error.js' {
  declare module.exports: $Exports<'braintree-web/lib/convert-to-braintree-error'>;
}
declare module 'braintree-web/lib/create-authorization-data.js' {
  declare module.exports: $Exports<'braintree-web/lib/create-authorization-data'>;
}
declare module 'braintree-web/lib/create-restricted-input.js' {
  declare module.exports: $Exports<'braintree-web/lib/create-restricted-input'>;
}
declare module 'braintree-web/lib/deferred.js' {
  declare module.exports: $Exports<'braintree-web/lib/deferred'>;
}
declare module 'braintree-web/lib/destructor.js' {
  declare module.exports: $Exports<'braintree-web/lib/destructor'>;
}
declare module 'braintree-web/lib/enumerate.js' {
  declare module.exports: $Exports<'braintree-web/lib/enumerate'>;
}
declare module 'braintree-web/lib/errors.js' {
  declare module.exports: $Exports<'braintree-web/lib/errors'>;
}
declare module 'braintree-web/lib/event-emitter.js' {
  declare module.exports: $Exports<'braintree-web/lib/event-emitter'>;
}
declare module 'braintree-web/lib/fake-restricted-input.js' {
  declare module.exports: $Exports<'braintree-web/lib/fake-restricted-input'>;
}
declare module 'braintree-web/lib/frame-service/external/frame-service.js' {
  declare module.exports: $Exports<'braintree-web/lib/frame-service/external/frame-service'>;
}
declare module 'braintree-web/lib/frame-service/external/index.js' {
  declare module.exports: $Exports<'braintree-web/lib/frame-service/external/index'>;
}
declare module 'braintree-web/lib/frame-service/external/strategies/modal.js' {
  declare module.exports: $Exports<'braintree-web/lib/frame-service/external/strategies/modal'>;
}
declare module 'braintree-web/lib/frame-service/external/strategies/popup-bridge.js' {
  declare module.exports: $Exports<'braintree-web/lib/frame-service/external/strategies/popup-bridge'>;
}
declare module 'braintree-web/lib/frame-service/external/strategies/popup/compose-options.js' {
  declare module.exports: $Exports<'braintree-web/lib/frame-service/external/strategies/popup/compose-options'>;
}
declare module 'braintree-web/lib/frame-service/external/strategies/popup/index.js' {
  declare module.exports: $Exports<'braintree-web/lib/frame-service/external/strategies/popup/index'>;
}
declare module 'braintree-web/lib/frame-service/external/strategies/popup/position.js' {
  declare module.exports: $Exports<'braintree-web/lib/frame-service/external/strategies/popup/position'>;
}
declare module 'braintree-web/lib/frame-service/shared/browser-detection.js' {
  declare module.exports: $Exports<'braintree-web/lib/frame-service/shared/browser-detection'>;
}
declare module 'braintree-web/lib/frame-service/shared/constants.js' {
  declare module.exports: $Exports<'braintree-web/lib/frame-service/shared/constants'>;
}
declare module 'braintree-web/lib/frame-service/shared/errors.js' {
  declare module.exports: $Exports<'braintree-web/lib/frame-service/shared/errors'>;
}
declare module 'braintree-web/lib/frame-service/shared/events.js' {
  declare module.exports: $Exports<'braintree-web/lib/frame-service/shared/events'>;
}
declare module 'braintree-web/lib/generate-google-pay-configuration.js' {
  declare module.exports: $Exports<'braintree-web/lib/generate-google-pay-configuration'>;
}
declare module 'braintree-web/lib/is-date-string-before-or-on.js' {
  declare module.exports: $Exports<'braintree-web/lib/is-date-string-before-or-on'>;
}
declare module 'braintree-web/lib/is-https.js' {
  declare module.exports: $Exports<'braintree-web/lib/is-https'>;
}
declare module 'braintree-web/lib/is-verified-domain.js' {
  declare module.exports: $Exports<'braintree-web/lib/is-verified-domain'>;
}
declare module 'braintree-web/lib/json-clone.js' {
  declare module.exports: $Exports<'braintree-web/lib/json-clone'>;
}
declare module 'braintree-web/lib/methods.js' {
  declare module.exports: $Exports<'braintree-web/lib/methods'>;
}
declare module 'braintree-web/lib/once.js' {
  declare module.exports: $Exports<'braintree-web/lib/once'>;
}
declare module 'braintree-web/lib/promise.js' {
  declare module.exports: $Exports<'braintree-web/lib/promise'>;
}
declare module 'braintree-web/lib/querystring.js' {
  declare module.exports: $Exports<'braintree-web/lib/querystring'>;
}
declare module 'braintree-web/lib/redirect.js' {
  declare module.exports: $Exports<'braintree-web/lib/redirect'>;
}
declare module 'braintree-web/lib/sanitize-html.js' {
  declare module.exports: $Exports<'braintree-web/lib/sanitize-html'>;
}
declare module 'braintree-web/lib/supports-passive-event-listener.js' {
  declare module.exports: $Exports<'braintree-web/lib/supports-passive-event-listener'>;
}
declare module 'braintree-web/lib/use-min.js' {
  declare module.exports: $Exports<'braintree-web/lib/use-min'>;
}
declare module 'braintree-web/lib/vendor/polyfill.js' {
  declare module.exports: $Exports<'braintree-web/lib/vendor/polyfill'>;
}
declare module 'braintree-web/lib/vendor/uuid.js' {
  declare module.exports: $Exports<'braintree-web/lib/vendor/uuid'>;
}
declare module 'braintree-web/masterpass/external/masterpass.js' {
  declare module.exports: $Exports<'braintree-web/masterpass/external/masterpass'>;
}
declare module 'braintree-web/masterpass/index.js' {
  declare module.exports: $Exports<'braintree-web/masterpass/index'>;
}
declare module 'braintree-web/masterpass/shared/browser-detection.js' {
  declare module.exports: $Exports<'braintree-web/masterpass/shared/browser-detection'>;
}
declare module 'braintree-web/masterpass/shared/constants.js' {
  declare module.exports: $Exports<'braintree-web/masterpass/shared/constants'>;
}
declare module 'braintree-web/masterpass/shared/errors.js' {
  declare module.exports: $Exports<'braintree-web/masterpass/shared/errors'>;
}
declare module 'braintree-web/payment-request/external/payment-request.js' {
  declare module.exports: $Exports<'braintree-web/payment-request/external/payment-request'>;
}
declare module 'braintree-web/payment-request/index.js' {
  declare module.exports: $Exports<'braintree-web/payment-request/index'>;
}
declare module 'braintree-web/payment-request/shared/constants.js' {
  declare module.exports: $Exports<'braintree-web/payment-request/shared/constants'>;
}
declare module 'braintree-web/payment-request/shared/errors.js' {
  declare module.exports: $Exports<'braintree-web/payment-request/shared/errors'>;
}
declare module 'braintree-web/paypal-checkout/errors.js' {
  declare module.exports: $Exports<'braintree-web/paypal-checkout/errors'>;
}
declare module 'braintree-web/paypal-checkout/index.js' {
  declare module.exports: $Exports<'braintree-web/paypal-checkout/index'>;
}
declare module 'braintree-web/paypal-checkout/paypal-checkout.js' {
  declare module.exports: $Exports<'braintree-web/paypal-checkout/paypal-checkout'>;
}
declare module 'braintree-web/paypal/external/paypal.js' {
  declare module.exports: $Exports<'braintree-web/paypal/external/paypal'>;
}
declare module 'braintree-web/paypal/index.js' {
  declare module.exports: $Exports<'braintree-web/paypal/index'>;
}
declare module 'braintree-web/paypal/shared/constants.js' {
  declare module.exports: $Exports<'braintree-web/paypal/shared/constants'>;
}
declare module 'braintree-web/paypal/shared/errors.js' {
  declare module.exports: $Exports<'braintree-web/paypal/shared/errors'>;
}
declare module 'braintree-web/three-d-secure/external/three-d-secure.js' {
  declare module.exports: $Exports<'braintree-web/three-d-secure/external/three-d-secure'>;
}
declare module 'braintree-web/three-d-secure/index.js' {
  declare module.exports: $Exports<'braintree-web/three-d-secure/index'>;
}
declare module 'braintree-web/three-d-secure/shared/constants.js' {
  declare module.exports: $Exports<'braintree-web/three-d-secure/shared/constants'>;
}
declare module 'braintree-web/three-d-secure/shared/errors.js' {
  declare module.exports: $Exports<'braintree-web/three-d-secure/shared/errors'>;
}
declare module 'braintree-web/three-d-secure/shared/events.js' {
  declare module.exports: $Exports<'braintree-web/three-d-secure/shared/events'>;
}
declare module 'braintree-web/unionpay/index.js' {
  declare module.exports: $Exports<'braintree-web/unionpay/index'>;
}
declare module 'braintree-web/unionpay/shared/constants.js' {
  declare module.exports: $Exports<'braintree-web/unionpay/shared/constants'>;
}
declare module 'braintree-web/unionpay/shared/errors.js' {
  declare module.exports: $Exports<'braintree-web/unionpay/shared/errors'>;
}
declare module 'braintree-web/unionpay/shared/unionpay.js' {
  declare module.exports: $Exports<'braintree-web/unionpay/shared/unionpay'>;
}
declare module 'braintree-web/us-bank-account/constants.js' {
  declare module.exports: $Exports<'braintree-web/us-bank-account/constants'>;
}
declare module 'braintree-web/us-bank-account/errors.js' {
  declare module.exports: $Exports<'braintree-web/us-bank-account/errors'>;
}
declare module 'braintree-web/us-bank-account/index.js' {
  declare module.exports: $Exports<'braintree-web/us-bank-account/index'>;
}
declare module 'braintree-web/us-bank-account/us-bank-account.js' {
  declare module.exports: $Exports<'braintree-web/us-bank-account/us-bank-account'>;
}
declare module 'braintree-web/vault-manager/errors.js' {
  declare module.exports: $Exports<'braintree-web/vault-manager/errors'>;
}
declare module 'braintree-web/vault-manager/index.js' {
  declare module.exports: $Exports<'braintree-web/vault-manager/index'>;
}
declare module 'braintree-web/vault-manager/vault-manager.js' {
  declare module.exports: $Exports<'braintree-web/vault-manager/vault-manager'>;
}
declare module 'braintree-web/venmo/index.js' {
  declare module.exports: $Exports<'braintree-web/venmo/index'>;
}
declare module 'braintree-web/venmo/shared/browser-detection.js' {
  declare module.exports: $Exports<'braintree-web/venmo/shared/browser-detection'>;
}
declare module 'braintree-web/venmo/shared/constants.js' {
  declare module.exports: $Exports<'braintree-web/venmo/shared/constants'>;
}
declare module 'braintree-web/venmo/shared/errors.js' {
  declare module.exports: $Exports<'braintree-web/venmo/shared/errors'>;
}
declare module 'braintree-web/venmo/shared/supports-venmo.js' {
  declare module.exports: $Exports<'braintree-web/venmo/shared/supports-venmo'>;
}
declare module 'braintree-web/venmo/venmo.js' {
  declare module.exports: $Exports<'braintree-web/venmo/venmo'>;
}
declare module 'braintree-web/visa-checkout/errors.js' {
  declare module.exports: $Exports<'braintree-web/visa-checkout/errors'>;
}
declare module 'braintree-web/visa-checkout/index.js' {
  declare module.exports: $Exports<'braintree-web/visa-checkout/index'>;
}
declare module 'braintree-web/visa-checkout/visa-checkout.js' {
  declare module.exports: $Exports<'braintree-web/visa-checkout/visa-checkout'>;
}
