// flow-typed signature: 3098f0c69d847b4ecf65434f17d1fa30
// flow-typed version: <<STUB>>/payment-icons_v^1.1.0/flow_v0.83.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'payment-icons'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'payment-icons' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'payment-icons/tests/dimensions.test' {
  declare module.exports: any;
}

declare module 'payment-icons/tests/security.test' {
  declare module.exports: any;
}

// Filename aliases
declare module 'payment-icons/tests/dimensions.test.js' {
  declare module.exports: $Exports<'payment-icons/tests/dimensions.test'>;
}
declare module 'payment-icons/tests/security.test.js' {
  declare module.exports: $Exports<'payment-icons/tests/security.test'>;
}
