// flow-typed signature: eee263fdd9cbb010099d9e83b978a8e7
// flow-typed version: <<STUB>>/paypal-checkout_v^4.0.202/flow_v0.83.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'paypal-checkout'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'paypal-checkout' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'paypal-checkout/__sdk__' {
  declare module.exports: any;
}

declare module 'paypal-checkout/dist/checkout.button.render' {
  declare module.exports: any;
}

declare module 'paypal-checkout/dist/checkout.lib' {
  declare module.exports: any;
}

declare module 'paypal-checkout/globals' {
  declare module.exports: any;
}

declare module 'paypal-checkout/src/api/hacks' {
  declare module.exports: any;
}

declare module 'paypal-checkout/src/api/index' {
  declare module.exports: any;
}

declare module 'paypal-checkout/src/api/rest' {
  declare module.exports: any;
}

declare module 'paypal-checkout/src/billing/index' {
  declare module.exports: any;
}

declare module 'paypal-checkout/src/billing/template/containerTemplate' {
  declare module.exports: any;
}

declare module 'paypal-checkout/src/billing/template/index' {
  declare module.exports: any;
}

declare module 'paypal-checkout/src/button/child' {
  declare module.exports: any;
}

declare module 'paypal-checkout/src/button/component' {
  declare module.exports: any;
}

declare module 'paypal-checkout/src/button/config' {
  declare module.exports: any;
}

declare module 'paypal-checkout/src/button/index' {
  declare module.exports: any;
}

declare module 'paypal-checkout/src/button/props' {
  declare module.exports: any;
}

declare module 'paypal-checkout/src/button/template/componentScript' {
  declare module.exports: any;
}

declare module 'paypal-checkout/src/button/template/componentStyle/base' {
  declare module.exports: any;
}

declare module 'paypal-checkout/src/button/template/componentStyle/branding' {
  declare module.exports: any;
}

declare module 'paypal-checkout/src/button/template/componentStyle/button' {
  declare module.exports: any;
}

declare module 'paypal-checkout/src/button/template/componentStyle/class' {
  declare module.exports: any;
}

declare module 'paypal-checkout/src/button/template/componentStyle/color' {
  declare module.exports: any;
}

declare module 'paypal-checkout/src/button/template/componentStyle/index' {
  declare module.exports: any;
}

declare module 'paypal-checkout/src/button/template/componentStyle/labels' {
  declare module.exports: any;
}

declare module 'paypal-checkout/src/button/template/componentStyle/layout' {
  declare module.exports: any;
}

declare module 'paypal-checkout/src/button/template/componentStyle/page' {
  declare module.exports: any;
}

declare module 'paypal-checkout/src/button/template/componentStyle/responsive' {
  declare module.exports: any;
}

declare module 'paypal-checkout/src/button/template/componentTemplate' {
  declare module.exports: any;
}

declare module 'paypal-checkout/src/button/template/containerTemplate' {
  declare module.exports: any;
}

declare module 'paypal-checkout/src/button/template/content' {
  declare module.exports: any;
}

declare module 'paypal-checkout/src/button/template/index' {
  declare module.exports: any;
}

declare module 'paypal-checkout/src/button/validate' {
  declare module.exports: any;
}

declare module 'paypal-checkout/src/card/index' {
  declare module.exports: any;
}

declare module 'paypal-checkout/src/checkout/component' {
  declare module.exports: any;
}

declare module 'paypal-checkout/src/checkout/index' {
  declare module.exports: any;
}

declare module 'paypal-checkout/src/checkout/template/componentTemplate' {
  declare module.exports: any;
}

declare module 'paypal-checkout/src/checkout/template/containerStyle/base' {
  declare module.exports: any;
}

declare module 'paypal-checkout/src/checkout/template/containerStyle/index' {
  declare module.exports: any;
}

declare module 'paypal-checkout/src/checkout/template/containerTemplate' {
  declare module.exports: any;
}

declare module 'paypal-checkout/src/checkout/template/index' {
  declare module.exports: any;
}

declare module 'paypal-checkout/src/checkout/template/sandboxStyle/base' {
  declare module.exports: any;
}

declare module 'paypal-checkout/src/checkout/template/sandboxStyle/index' {
  declare module.exports: any;
}

declare module 'paypal-checkout/src/compat/fallback' {
  declare module.exports: any;
}

declare module 'paypal-checkout/src/compat/index' {
  declare module.exports: any;
}

declare module 'paypal-checkout/src/config/config' {
  declare module.exports: any;
}

declare module 'paypal-checkout/src/config/index' {
  declare module.exports: any;
}

declare module 'paypal-checkout/src/constants/button' {
  declare module.exports: any;
}

declare module 'paypal-checkout/src/constants/checkout' {
  declare module.exports: any;
}

declare module 'paypal-checkout/src/constants/country' {
  declare module.exports: any;
}

declare module 'paypal-checkout/src/constants/fpti' {
  declare module.exports: any;
}

declare module 'paypal-checkout/src/constants/funding' {
  declare module.exports: any;
}

declare module 'paypal-checkout/src/constants/index' {
  declare module.exports: any;
}

declare module 'paypal-checkout/src/constants/misc' {
  declare module.exports: any;
}

declare module 'paypal-checkout/src/declarations' {
  declare module.exports: any;
}

declare module 'paypal-checkout/src/experiments' {
  declare module.exports: any;
}

declare module 'paypal-checkout/src/external/index' {
  declare module.exports: any;
}

declare module 'paypal-checkout/src/external/pptm' {
  declare module.exports: any;
}

declare module 'paypal-checkout/src/funding/config' {
  declare module.exports: any;
}

declare module 'paypal-checkout/src/funding/funding' {
  declare module.exports: any;
}

declare module 'paypal-checkout/src/funding/index' {
  declare module.exports: any;
}

declare module 'paypal-checkout/src/hacks' {
  declare module.exports: any;
}

declare module 'paypal-checkout/src/index' {
  declare module.exports: any;
}

declare module 'paypal-checkout/src/integrations/braintree' {
  declare module.exports: any;
}

declare module 'paypal-checkout/src/integrations/checkout' {
  declare module.exports: any;
}

declare module 'paypal-checkout/src/integrations/index' {
  declare module.exports: any;
}

declare module 'paypal-checkout/src/integrations/popupBridge' {
  declare module.exports: any;
}

declare module 'paypal-checkout/src/interface' {
  declare module.exports: any;
}

declare module 'paypal-checkout/src/legacy/button' {
  declare module.exports: any;
}

declare module 'paypal-checkout/src/legacy/common' {
  declare module.exports: any;
}

declare module 'paypal-checkout/src/legacy/constants' {
  declare module.exports: any;
}

declare module 'paypal-checkout/src/legacy/eligibility' {
  declare module.exports: any;
}

declare module 'paypal-checkout/src/legacy/index' {
  declare module.exports: any;
}

declare module 'paypal-checkout/src/legacy/interface' {
  declare module.exports: any;
}

declare module 'paypal-checkout/src/legacy/options' {
  declare module.exports: any;
}

declare module 'paypal-checkout/src/legacy/postBridge' {
  declare module.exports: any;
}

declare module 'paypal-checkout/src/legacy/ready' {
  declare module.exports: any;
}

declare module 'paypal-checkout/src/legacy/util' {
  declare module.exports: any;
}

declare module 'paypal-checkout/src/lib/a11y' {
  declare module.exports: any;
}

declare module 'paypal-checkout/src/lib/beacon' {
  declare module.exports: any;
}

declare module 'paypal-checkout/src/lib/device' {
  declare module.exports: any;
}

declare module 'paypal-checkout/src/lib/dom' {
  declare module.exports: any;
}

declare module 'paypal-checkout/src/lib/eligibility' {
  declare module.exports: any;
}

declare module 'paypal-checkout/src/lib/errors' {
  declare module.exports: any;
}

declare module 'paypal-checkout/src/lib/funding' {
  declare module.exports: any;
}

declare module 'paypal-checkout/src/lib/http' {
  declare module.exports: any;
}

declare module 'paypal-checkout/src/lib/index' {
  declare module.exports: any;
}

declare module 'paypal-checkout/src/lib/jsx' {
  declare module.exports: any;
}

declare module 'paypal-checkout/src/lib/logger' {
  declare module.exports: any;
}

declare module 'paypal-checkout/src/lib/meta' {
  declare module.exports: any;
}

declare module 'paypal-checkout/src/lib/namespace' {
  declare module.exports: any;
}

declare module 'paypal-checkout/src/lib/proxy' {
  declare module.exports: any;
}

declare module 'paypal-checkout/src/lib/script' {
  declare module.exports: any;
}

declare module 'paypal-checkout/src/lib/security' {
  declare module.exports: any;
}

declare module 'paypal-checkout/src/lib/session' {
  declare module.exports: any;
}

declare module 'paypal-checkout/src/lib/throttle' {
  declare module.exports: any;
}

declare module 'paypal-checkout/src/lib/util' {
  declare module.exports: any;
}

declare module 'paypal-checkout/src/load' {
  declare module.exports: any;
}

declare module 'paypal-checkout/src/loader/component' {
  declare module.exports: any;
}

declare module 'paypal-checkout/src/loader/config' {
  declare module.exports: any;
}

declare module 'paypal-checkout/src/loader/index' {
  declare module.exports: any;
}

declare module 'paypal-checkout/src/loader/interface' {
  declare module.exports: any;
}

declare module 'paypal-checkout/src/loader/load' {
  declare module.exports: any;
}

declare module 'paypal-checkout/src/loader/responder' {
  declare module.exports: any;
}

declare module 'paypal-checkout/src/loader/util' {
  declare module.exports: any;
}

declare module 'paypal-checkout/src/resources/cardLogos/index' {
  declare module.exports: any;
}

declare module 'paypal-checkout/src/resources/fundingLogos/bancontact' {
  declare module.exports: any;
}

declare module 'paypal-checkout/src/resources/fundingLogos/credit' {
  declare module.exports: any;
}

declare module 'paypal-checkout/src/resources/fundingLogos/eps' {
  declare module.exports: any;
}

declare module 'paypal-checkout/src/resources/fundingLogos/giropay' {
  declare module.exports: any;
}

declare module 'paypal-checkout/src/resources/fundingLogos/ideal' {
  declare module.exports: any;
}

declare module 'paypal-checkout/src/resources/fundingLogos/index' {
  declare module.exports: any;
}

declare module 'paypal-checkout/src/resources/fundingLogos/mybank' {
  declare module.exports: any;
}

declare module 'paypal-checkout/src/resources/fundingLogos/p24' {
  declare module.exports: any;
}

declare module 'paypal-checkout/src/resources/fundingLogos/paypal' {
  declare module.exports: any;
}

declare module 'paypal-checkout/src/resources/fundingLogos/sofort' {
  declare module.exports: any;
}

declare module 'paypal-checkout/src/resources/fundingLogos/zimpler' {
  declare module.exports: any;
}

declare module 'paypal-checkout/src/resources/index' {
  declare module.exports: any;
}

declare module 'paypal-checkout/src/setup' {
  declare module.exports: any;
}

declare module 'paypal-checkout/src/types' {
  declare module.exports: any;
}

// Filename aliases
declare module 'paypal-checkout/__sdk__.js' {
  declare module.exports: $Exports<'paypal-checkout/__sdk__'>;
}
declare module 'paypal-checkout/dist/checkout.button.render.js' {
  declare module.exports: $Exports<'paypal-checkout/dist/checkout.button.render'>;
}
declare module 'paypal-checkout/dist/checkout.lib.js' {
  declare module.exports: $Exports<'paypal-checkout/dist/checkout.lib'>;
}
declare module 'paypal-checkout/globals.js' {
  declare module.exports: $Exports<'paypal-checkout/globals'>;
}
declare module 'paypal-checkout/index' {
  declare module.exports: $Exports<'paypal-checkout'>;
}
declare module 'paypal-checkout/index.js' {
  declare module.exports: $Exports<'paypal-checkout'>;
}
declare module 'paypal-checkout/src/api/hacks.js' {
  declare module.exports: $Exports<'paypal-checkout/src/api/hacks'>;
}
declare module 'paypal-checkout/src/api/index.js' {
  declare module.exports: $Exports<'paypal-checkout/src/api/index'>;
}
declare module 'paypal-checkout/src/api/rest.js' {
  declare module.exports: $Exports<'paypal-checkout/src/api/rest'>;
}
declare module 'paypal-checkout/src/billing/index.js' {
  declare module.exports: $Exports<'paypal-checkout/src/billing/index'>;
}
declare module 'paypal-checkout/src/billing/template/containerTemplate.jsx' {
  declare module.exports: $Exports<'paypal-checkout/src/billing/template/containerTemplate'>;
}
declare module 'paypal-checkout/src/billing/template/index.js' {
  declare module.exports: $Exports<'paypal-checkout/src/billing/template/index'>;
}
declare module 'paypal-checkout/src/button/child.js' {
  declare module.exports: $Exports<'paypal-checkout/src/button/child'>;
}
declare module 'paypal-checkout/src/button/component.jsx' {
  declare module.exports: $Exports<'paypal-checkout/src/button/component'>;
}
declare module 'paypal-checkout/src/button/config.js' {
  declare module.exports: $Exports<'paypal-checkout/src/button/config'>;
}
declare module 'paypal-checkout/src/button/index.js' {
  declare module.exports: $Exports<'paypal-checkout/src/button/index'>;
}
declare module 'paypal-checkout/src/button/props.js' {
  declare module.exports: $Exports<'paypal-checkout/src/button/props'>;
}
declare module 'paypal-checkout/src/button/template/componentScript.js' {
  declare module.exports: $Exports<'paypal-checkout/src/button/template/componentScript'>;
}
declare module 'paypal-checkout/src/button/template/componentStyle/base.js' {
  declare module.exports: $Exports<'paypal-checkout/src/button/template/componentStyle/base'>;
}
declare module 'paypal-checkout/src/button/template/componentStyle/branding.js' {
  declare module.exports: $Exports<'paypal-checkout/src/button/template/componentStyle/branding'>;
}
declare module 'paypal-checkout/src/button/template/componentStyle/button.js' {
  declare module.exports: $Exports<'paypal-checkout/src/button/template/componentStyle/button'>;
}
declare module 'paypal-checkout/src/button/template/componentStyle/class.js' {
  declare module.exports: $Exports<'paypal-checkout/src/button/template/componentStyle/class'>;
}
declare module 'paypal-checkout/src/button/template/componentStyle/color.js' {
  declare module.exports: $Exports<'paypal-checkout/src/button/template/componentStyle/color'>;
}
declare module 'paypal-checkout/src/button/template/componentStyle/index.js' {
  declare module.exports: $Exports<'paypal-checkout/src/button/template/componentStyle/index'>;
}
declare module 'paypal-checkout/src/button/template/componentStyle/labels.js' {
  declare module.exports: $Exports<'paypal-checkout/src/button/template/componentStyle/labels'>;
}
declare module 'paypal-checkout/src/button/template/componentStyle/layout.js' {
  declare module.exports: $Exports<'paypal-checkout/src/button/template/componentStyle/layout'>;
}
declare module 'paypal-checkout/src/button/template/componentStyle/page.js' {
  declare module.exports: $Exports<'paypal-checkout/src/button/template/componentStyle/page'>;
}
declare module 'paypal-checkout/src/button/template/componentStyle/responsive.js' {
  declare module.exports: $Exports<'paypal-checkout/src/button/template/componentStyle/responsive'>;
}
declare module 'paypal-checkout/src/button/template/componentTemplate.jsx' {
  declare module.exports: $Exports<'paypal-checkout/src/button/template/componentTemplate'>;
}
declare module 'paypal-checkout/src/button/template/containerTemplate.jsx' {
  declare module.exports: $Exports<'paypal-checkout/src/button/template/containerTemplate'>;
}
declare module 'paypal-checkout/src/button/template/content.js' {
  declare module.exports: $Exports<'paypal-checkout/src/button/template/content'>;
}
declare module 'paypal-checkout/src/button/template/index.js' {
  declare module.exports: $Exports<'paypal-checkout/src/button/template/index'>;
}
declare module 'paypal-checkout/src/button/validate.js' {
  declare module.exports: $Exports<'paypal-checkout/src/button/validate'>;
}
declare module 'paypal-checkout/src/card/index.js' {
  declare module.exports: $Exports<'paypal-checkout/src/card/index'>;
}
declare module 'paypal-checkout/src/checkout/component.js' {
  declare module.exports: $Exports<'paypal-checkout/src/checkout/component'>;
}
declare module 'paypal-checkout/src/checkout/index.js' {
  declare module.exports: $Exports<'paypal-checkout/src/checkout/index'>;
}
declare module 'paypal-checkout/src/checkout/template/componentTemplate.jsx' {
  declare module.exports: $Exports<'paypal-checkout/src/checkout/template/componentTemplate'>;
}
declare module 'paypal-checkout/src/checkout/template/containerStyle/base.js' {
  declare module.exports: $Exports<'paypal-checkout/src/checkout/template/containerStyle/base'>;
}
declare module 'paypal-checkout/src/checkout/template/containerStyle/index.js' {
  declare module.exports: $Exports<'paypal-checkout/src/checkout/template/containerStyle/index'>;
}
declare module 'paypal-checkout/src/checkout/template/containerTemplate.jsx' {
  declare module.exports: $Exports<'paypal-checkout/src/checkout/template/containerTemplate'>;
}
declare module 'paypal-checkout/src/checkout/template/index.js' {
  declare module.exports: $Exports<'paypal-checkout/src/checkout/template/index'>;
}
declare module 'paypal-checkout/src/checkout/template/sandboxStyle/base.js' {
  declare module.exports: $Exports<'paypal-checkout/src/checkout/template/sandboxStyle/base'>;
}
declare module 'paypal-checkout/src/checkout/template/sandboxStyle/index.js' {
  declare module.exports: $Exports<'paypal-checkout/src/checkout/template/sandboxStyle/index'>;
}
declare module 'paypal-checkout/src/compat/fallback.js' {
  declare module.exports: $Exports<'paypal-checkout/src/compat/fallback'>;
}
declare module 'paypal-checkout/src/compat/index.js' {
  declare module.exports: $Exports<'paypal-checkout/src/compat/index'>;
}
declare module 'paypal-checkout/src/config/config.js' {
  declare module.exports: $Exports<'paypal-checkout/src/config/config'>;
}
declare module 'paypal-checkout/src/config/index.js' {
  declare module.exports: $Exports<'paypal-checkout/src/config/index'>;
}
declare module 'paypal-checkout/src/constants/button.js' {
  declare module.exports: $Exports<'paypal-checkout/src/constants/button'>;
}
declare module 'paypal-checkout/src/constants/checkout.js' {
  declare module.exports: $Exports<'paypal-checkout/src/constants/checkout'>;
}
declare module 'paypal-checkout/src/constants/country.js' {
  declare module.exports: $Exports<'paypal-checkout/src/constants/country'>;
}
declare module 'paypal-checkout/src/constants/fpti.js' {
  declare module.exports: $Exports<'paypal-checkout/src/constants/fpti'>;
}
declare module 'paypal-checkout/src/constants/funding.js' {
  declare module.exports: $Exports<'paypal-checkout/src/constants/funding'>;
}
declare module 'paypal-checkout/src/constants/index.js' {
  declare module.exports: $Exports<'paypal-checkout/src/constants/index'>;
}
declare module 'paypal-checkout/src/constants/misc.js' {
  declare module.exports: $Exports<'paypal-checkout/src/constants/misc'>;
}
declare module 'paypal-checkout/src/declarations.js' {
  declare module.exports: $Exports<'paypal-checkout/src/declarations'>;
}
declare module 'paypal-checkout/src/experiments.js' {
  declare module.exports: $Exports<'paypal-checkout/src/experiments'>;
}
declare module 'paypal-checkout/src/external/index.js' {
  declare module.exports: $Exports<'paypal-checkout/src/external/index'>;
}
declare module 'paypal-checkout/src/external/pptm.js' {
  declare module.exports: $Exports<'paypal-checkout/src/external/pptm'>;
}
declare module 'paypal-checkout/src/funding/config.js' {
  declare module.exports: $Exports<'paypal-checkout/src/funding/config'>;
}
declare module 'paypal-checkout/src/funding/funding.js' {
  declare module.exports: $Exports<'paypal-checkout/src/funding/funding'>;
}
declare module 'paypal-checkout/src/funding/index.js' {
  declare module.exports: $Exports<'paypal-checkout/src/funding/index'>;
}
declare module 'paypal-checkout/src/hacks.js' {
  declare module.exports: $Exports<'paypal-checkout/src/hacks'>;
}
declare module 'paypal-checkout/src/index.js' {
  declare module.exports: $Exports<'paypal-checkout/src/index'>;
}
declare module 'paypal-checkout/src/integrations/braintree.js' {
  declare module.exports: $Exports<'paypal-checkout/src/integrations/braintree'>;
}
declare module 'paypal-checkout/src/integrations/checkout.js' {
  declare module.exports: $Exports<'paypal-checkout/src/integrations/checkout'>;
}
declare module 'paypal-checkout/src/integrations/index.js' {
  declare module.exports: $Exports<'paypal-checkout/src/integrations/index'>;
}
declare module 'paypal-checkout/src/integrations/popupBridge.js' {
  declare module.exports: $Exports<'paypal-checkout/src/integrations/popupBridge'>;
}
declare module 'paypal-checkout/src/interface.js' {
  declare module.exports: $Exports<'paypal-checkout/src/interface'>;
}
declare module 'paypal-checkout/src/legacy/button.js' {
  declare module.exports: $Exports<'paypal-checkout/src/legacy/button'>;
}
declare module 'paypal-checkout/src/legacy/common.js' {
  declare module.exports: $Exports<'paypal-checkout/src/legacy/common'>;
}
declare module 'paypal-checkout/src/legacy/constants.js' {
  declare module.exports: $Exports<'paypal-checkout/src/legacy/constants'>;
}
declare module 'paypal-checkout/src/legacy/eligibility.js' {
  declare module.exports: $Exports<'paypal-checkout/src/legacy/eligibility'>;
}
declare module 'paypal-checkout/src/legacy/index.js' {
  declare module.exports: $Exports<'paypal-checkout/src/legacy/index'>;
}
declare module 'paypal-checkout/src/legacy/interface.js' {
  declare module.exports: $Exports<'paypal-checkout/src/legacy/interface'>;
}
declare module 'paypal-checkout/src/legacy/options.js' {
  declare module.exports: $Exports<'paypal-checkout/src/legacy/options'>;
}
declare module 'paypal-checkout/src/legacy/postBridge.js' {
  declare module.exports: $Exports<'paypal-checkout/src/legacy/postBridge'>;
}
declare module 'paypal-checkout/src/legacy/ready.js' {
  declare module.exports: $Exports<'paypal-checkout/src/legacy/ready'>;
}
declare module 'paypal-checkout/src/legacy/util.js' {
  declare module.exports: $Exports<'paypal-checkout/src/legacy/util'>;
}
declare module 'paypal-checkout/src/lib/a11y.js' {
  declare module.exports: $Exports<'paypal-checkout/src/lib/a11y'>;
}
declare module 'paypal-checkout/src/lib/beacon.js' {
  declare module.exports: $Exports<'paypal-checkout/src/lib/beacon'>;
}
declare module 'paypal-checkout/src/lib/device.js' {
  declare module.exports: $Exports<'paypal-checkout/src/lib/device'>;
}
declare module 'paypal-checkout/src/lib/dom.js' {
  declare module.exports: $Exports<'paypal-checkout/src/lib/dom'>;
}
declare module 'paypal-checkout/src/lib/eligibility.js' {
  declare module.exports: $Exports<'paypal-checkout/src/lib/eligibility'>;
}
declare module 'paypal-checkout/src/lib/errors.js' {
  declare module.exports: $Exports<'paypal-checkout/src/lib/errors'>;
}
declare module 'paypal-checkout/src/lib/funding.js' {
  declare module.exports: $Exports<'paypal-checkout/src/lib/funding'>;
}
declare module 'paypal-checkout/src/lib/http.js' {
  declare module.exports: $Exports<'paypal-checkout/src/lib/http'>;
}
declare module 'paypal-checkout/src/lib/index.js' {
  declare module.exports: $Exports<'paypal-checkout/src/lib/index'>;
}
declare module 'paypal-checkout/src/lib/jsx.js' {
  declare module.exports: $Exports<'paypal-checkout/src/lib/jsx'>;
}
declare module 'paypal-checkout/src/lib/logger.js' {
  declare module.exports: $Exports<'paypal-checkout/src/lib/logger'>;
}
declare module 'paypal-checkout/src/lib/meta.js' {
  declare module.exports: $Exports<'paypal-checkout/src/lib/meta'>;
}
declare module 'paypal-checkout/src/lib/namespace.js' {
  declare module.exports: $Exports<'paypal-checkout/src/lib/namespace'>;
}
declare module 'paypal-checkout/src/lib/proxy.js' {
  declare module.exports: $Exports<'paypal-checkout/src/lib/proxy'>;
}
declare module 'paypal-checkout/src/lib/script.js' {
  declare module.exports: $Exports<'paypal-checkout/src/lib/script'>;
}
declare module 'paypal-checkout/src/lib/security.js' {
  declare module.exports: $Exports<'paypal-checkout/src/lib/security'>;
}
declare module 'paypal-checkout/src/lib/session.js' {
  declare module.exports: $Exports<'paypal-checkout/src/lib/session'>;
}
declare module 'paypal-checkout/src/lib/throttle.js' {
  declare module.exports: $Exports<'paypal-checkout/src/lib/throttle'>;
}
declare module 'paypal-checkout/src/lib/util.js' {
  declare module.exports: $Exports<'paypal-checkout/src/lib/util'>;
}
declare module 'paypal-checkout/src/load.js' {
  declare module.exports: $Exports<'paypal-checkout/src/load'>;
}
declare module 'paypal-checkout/src/loader/component.js' {
  declare module.exports: $Exports<'paypal-checkout/src/loader/component'>;
}
declare module 'paypal-checkout/src/loader/config.js' {
  declare module.exports: $Exports<'paypal-checkout/src/loader/config'>;
}
declare module 'paypal-checkout/src/loader/index.js' {
  declare module.exports: $Exports<'paypal-checkout/src/loader/index'>;
}
declare module 'paypal-checkout/src/loader/interface.js' {
  declare module.exports: $Exports<'paypal-checkout/src/loader/interface'>;
}
declare module 'paypal-checkout/src/loader/load.js' {
  declare module.exports: $Exports<'paypal-checkout/src/loader/load'>;
}
declare module 'paypal-checkout/src/loader/responder.js' {
  declare module.exports: $Exports<'paypal-checkout/src/loader/responder'>;
}
declare module 'paypal-checkout/src/loader/util.js' {
  declare module.exports: $Exports<'paypal-checkout/src/loader/util'>;
}
declare module 'paypal-checkout/src/resources/cardLogos/index.js' {
  declare module.exports: $Exports<'paypal-checkout/src/resources/cardLogos/index'>;
}
declare module 'paypal-checkout/src/resources/fundingLogos/bancontact.jsx' {
  declare module.exports: $Exports<'paypal-checkout/src/resources/fundingLogos/bancontact'>;
}
declare module 'paypal-checkout/src/resources/fundingLogos/credit.jsx' {
  declare module.exports: $Exports<'paypal-checkout/src/resources/fundingLogos/credit'>;
}
declare module 'paypal-checkout/src/resources/fundingLogos/eps.jsx' {
  declare module.exports: $Exports<'paypal-checkout/src/resources/fundingLogos/eps'>;
}
declare module 'paypal-checkout/src/resources/fundingLogos/giropay.jsx' {
  declare module.exports: $Exports<'paypal-checkout/src/resources/fundingLogos/giropay'>;
}
declare module 'paypal-checkout/src/resources/fundingLogos/ideal.jsx' {
  declare module.exports: $Exports<'paypal-checkout/src/resources/fundingLogos/ideal'>;
}
declare module 'paypal-checkout/src/resources/fundingLogos/index.js' {
  declare module.exports: $Exports<'paypal-checkout/src/resources/fundingLogos/index'>;
}
declare module 'paypal-checkout/src/resources/fundingLogos/mybank.jsx' {
  declare module.exports: $Exports<'paypal-checkout/src/resources/fundingLogos/mybank'>;
}
declare module 'paypal-checkout/src/resources/fundingLogos/p24.jsx' {
  declare module.exports: $Exports<'paypal-checkout/src/resources/fundingLogos/p24'>;
}
declare module 'paypal-checkout/src/resources/fundingLogos/paypal.jsx' {
  declare module.exports: $Exports<'paypal-checkout/src/resources/fundingLogos/paypal'>;
}
declare module 'paypal-checkout/src/resources/fundingLogos/sofort.jsx' {
  declare module.exports: $Exports<'paypal-checkout/src/resources/fundingLogos/sofort'>;
}
declare module 'paypal-checkout/src/resources/fundingLogos/zimpler.jsx' {
  declare module.exports: $Exports<'paypal-checkout/src/resources/fundingLogos/zimpler'>;
}
declare module 'paypal-checkout/src/resources/index.js' {
  declare module.exports: $Exports<'paypal-checkout/src/resources/index'>;
}
declare module 'paypal-checkout/src/setup.js' {
  declare module.exports: $Exports<'paypal-checkout/src/setup'>;
}
declare module 'paypal-checkout/src/types.js' {
  declare module.exports: $Exports<'paypal-checkout/src/types'>;
}
