# Welcome to Serverless!
#
# This file is the main config file for your service.
# It's very minimal at this point and uses default values.
# You can always add more config options for more control.
# We've included some commented out config examples here.
# Just uncomment any of them to get that config option.
#
# For full config options, check the docs:
#    docs.serverless.com
#
# Happy Coding!

service: mailserver

# You can pin your service to only deploy with a specific Serverless version
# Check out our docs for more details
# frameworkVersion:        "=X.X.X"

plugins:
  - serverless-offline
  - serverless-domain-manager

provider:
  name: aws
  runtime: nodejs6.10
  stage: ${opt:stage, 'development'}
  region: us-east-1
  environment:
    STAGE: ${self:provider.stage}
    NODE_ENV: ${self:provider.stage}
    MAILGUN_API_KEY: ${file(./env.${self:provider.stage}.json):MAILGUN_API_KEY}
    MAILGUN_DOMAIN: ${file(./env.${self:provider.stage}.json):MAILGUN_DOMAIN}
    MAILGUN_DEV_RECIPIENT: ${file(./env.${self:provider.stage}.json):MAILGUN_DEV_RECIPIENT}
    REQUEST_API_KEY: ${file(./env.${self:provider.stage}.json):REQUEST_API_KEY}

package:
  exclude:
    - __tests__/**

functions:
  server:
    handler: build/app.cjs.handler
    events:
      - http: ANY /
        cors: true
      - http: 'ANY {proxy+}'
        cors: true

packagePath: './package.json'
customDomain:
  domainName: ${self:provider.stage}-mail.artetexture.com
  basePath: ''
  stage: ${self:provider.stage}
  createRoute53Record: true
